/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Objects.*;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Erick Cordero
 */
public class VBuscarArticuloPorNombre extends javax.swing.JFrame {
//private Inventario inventario;
    /**
     * Creates new form VBuscarArticuloPorNombre
     */
    public VBuscarArticuloPorNombre() {
        initComponents();
        formateaGrid();
        //tableInventario.setAutoResizeMode(JTable.AUTO_RESIZE_ON);
       
        
        // inventario=null;
         clpdv = new CLPDV();
         
         txtNombreArticulo.grabFocus();
         this.setLocationRelativeTo(null);
          try {
              tableInventario.setModel(clpdv.getInventarioTableModel());
              formateaGrid();
          } catch (PDVException e){
            JOptionPane.showMessageDialog(this,e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
          }
    }
   
   public void formateaGrid(){
        tableInventario.getColumnModel().getColumn(0).setPreferredWidth(80);
        tableInventario.getColumnModel().getColumn(1).setPreferredWidth(350);
        tableInventario.getColumnModel().getColumn(2).setPreferredWidth(50);
        tableInventario.getColumnModel().getColumn(3).setPreferredWidth(100);
        tableInventario.getColumnModel().getColumn(4).setPreferredWidth(100);
        //tableInventario.getColumnModel().getColumn(5).setPreferredWidth(50);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTipoTransaccion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNombreArticulo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableInventario = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));
        setIconImage(getIconImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Articulo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 55, -1, -1));

        txtNombreArticulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNombreArticulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreArticuloKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreArticuloKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreArticuloKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombreArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 50, 493, 25));

        tableInventario.setModel(new InventarioTableModel());
        tableInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableInventarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableInventario);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 102, 880, 261));

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setMaximumSize(new java.awt.Dimension(911, 374));
        jPanel2.setMinimumSize(new java.awt.Dimension(911, 374));
        jPanel2.setPreferredSize(new java.awt.Dimension(911, 374));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/undo.png"))); // NOI18N
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 40, 40));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 40, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
       buscarArticulo();
    }//GEN-LAST:event_btnBuscarActionPerformed

    public void buscarArticulo(){
         String nombre = txtNombreArticulo.getText();
        try {
            tableInventario.setModel(clpdv.getBuscarInventarioTableModel(nombre));
            formateaGrid();
            
        } catch (PDVException e){
            JOptionPane.showMessageDialog(this,e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
         salir();
   
    }//GEN-LAST:event_btnRegresarActionPerformed
   
   public void salir(){
      
       
        Inventario unInventario=null;
         unInventario=encontrarArticulo();
        if(unInventario==null){
          dispose();
          if(txtTipoTransaccion.getText().equals("COMPRAS")){
              VCompras.txtCantidad.grabFocus();
              
          }else{
              if(txtTipoTransaccion.getText().equals("VENTAS")){
                  VVentas.txtCantidad.grabFocus();
              }
          }
        }else{
            if(txtTipoTransaccion.getText().equals("COMPRAS")){    
             dispose();
             VCompras.txtIdArticulo.setText(unInventario.getIdArticulo());
             VCompras.txtArticulo.setText(unInventario.getNombreProducto());
             VCompras.txtCantidadActual.setText(Integer.toString(unInventario.getCantidad()));
             VCompras.txtPrecioCompra.setText((unInventario.getPrecioCompraUnd()));
             VCompras.txtPrecioVenta.setText((unInventario.getPrecioVentaUnd()));
             VCompras.txtCantidad.grabFocus();
             
            }else{
                
                if(txtTipoTransaccion.getText().equals("VENTAS")){
                    dispose();
                    DecimalFormat formato=new DecimalFormat("###,##.##");
                    VVentas.txtIdArticulo.setText(unInventario.getIdArticulo());
                    VVentas.txtArticulo.setText(unInventario.getNombreProducto());
                    VVentas.txtPrecioVenta.setText((unInventario.getPrecioVentaUnd()));
                    VVentas.txtCantidadInventario.setText(Integer.toString(unInventario.getCantidad()));
                    
                    VVentas.txtCantidad.grabFocus();
                    }
                }
        }
   }
    public Inventario encontrarArticulo(){
       Inventario unInventario=null;
        int row = tableInventario.getSelectedRow();
        if (row > -1){
            InventarioTableModel itm = (InventarioTableModel)tableInventario.getModel();
            unInventario = itm.getInventario(row);
           
        }        
        return unInventario;
       
        
        
    }
    private void txtNombreArticuloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreArticuloKeyReleased
        // TODO add your handling code here:
        buscarArticulo();
    }//GEN-LAST:event_txtNombreArticuloKeyReleased

    private void txtNombreArticuloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreArticuloKeyTyped
         // TODO add your handling code here:
         char charecter = evt.getKeyChar();
        if (Character.isLowerCase(charecter)) {
            evt.setKeyChar(Character.toUpperCase(charecter));
        }
    }//GEN-LAST:event_txtNombreArticuloKeyTyped

    private void tableInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableInventarioMouseClicked
        // TODO add your handling code here:
         encontrarArticulo();
         salir();
        
    }//GEN-LAST:event_tableInventarioMouseClicked

    private void txtNombreArticuloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreArticuloKeyPressed
        // TODO add your handling code here:
         if(KeyEvent.getKeyText(evt.getKeyCode()).equals("Escape")){
            dispose();
         }
    }//GEN-LAST:event_txtNombreArticuloKeyPressed

    /**
     * @param args the command line arguments
     */
    private CLPDV clpdv;
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VBuscarArticuloPorNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VBuscarArticuloPorNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VBuscarArticuloPorNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VBuscarArticuloPorNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VBuscarArticuloPorNombre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tableInventario;
    private javax.swing.JTextField txtNombreArticulo;
    public static javax.swing.JTextField txtTipoTransaccion;
    // End of variables declaration//GEN-END:variables
}
