/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Objects.*;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;

/**
 *
 * @author Erick Cordero
 */
public class VCierreCajaDiario extends javax.swing.JFrame {
private Ventas venta;
private ArrayList<Ventas> unaVenta;
private Account unaCuenta;
private OpcionesUsuario unUsuario;
private Usuario usuario;
    /**
     * Creates new form VCierreCajaDiario
     */
    public VCierreCajaDiario() throws Exception {
        initComponents();
        this.setLocationRelativeTo(null);
        clpdv =new CLPDV();
        unaCuenta=null;
        unUsuario=null;
        usuario=null;
        dpFechaHoy.setDateToToday();
        calcularCierre();
        txtTotalEfectivo.setHorizontalAlignment(JTextField.RIGHT);
        txtTotalCredito.setHorizontalAlignment(JTextField.RIGHT);
        txtTotalTarjeta.setHorizontalAlignment(JTextField.RIGHT);
    }
    public void cerrar(){
         dispose();
         VReportes reportes = new VReportes();
         reportes.setVisible(true);
         VReportes.txtUsuario.setText(txtUsuario.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsuario = new javax.swing.JTextField();
        dpFechaHoy = new com.github.lgooddatepicker.components.DatePicker();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTotalEfectivo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTotalCredito = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTotalTarjeta = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1045, 439));
        setMinimumSize(new java.awt.Dimension(1045, 439));
        setPreferredSize(new java.awt.Dimension(1045, 439));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dpFechaHoy.setEnabled(false);
        dpFechaHoy.setMaximumSize(new java.awt.Dimension(1400, 979));
        dpFechaHoy.setMinimumSize(new java.awt.Dimension(1400, 979));
        dpFechaHoy.setPreferredSize(new java.awt.Dimension(1400, 979));
        getContentPane().add(dpFechaHoy, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 257, 32));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Cierre de Caja Diario");
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel2.setText("Total Efectivo:");
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtTotalEfectivo.setEditable(false);
        txtTotalEfectivo.setBackground(new java.awt.Color(153, 255, 153));
        txtTotalEfectivo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTotalEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalEfectivoActionPerformed(evt);
            }
        });

        jLabel3.setText("Total Credito:");
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtTotalCredito.setEditable(false);
        txtTotalCredito.setBackground(new java.awt.Color(153, 255, 153));
        txtTotalCredito.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel4.setText("Total Tarjeta:");
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtTotalTarjeta.setEditable(false);
        txtTotalTarjeta.setBackground(new java.awt.Color(153, 255, 153));
        txtTotalTarjeta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnSalir.setText("Salir");
        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtTotalCredito, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTotalEfectivo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTotalTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTotalEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTotalCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTotalTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 640, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        cerrar();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtTotalEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalEfectivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalEfectivoActionPerformed

    /**
     * @param args the command line arguments
     */
    private CLPDV clpdv;
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VCierreCajaDiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VCierreCajaDiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VCierreCajaDiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VCierreCajaDiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VCierreCajaDiario().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(VCierreCajaDiario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    public void calcularCierre() throws Exception{
        float totalContado=0;
        float totalCredito=0;
        float totalTarjeta=0;
        float totalContadoFlt=0;
        float totalCreditoFlt=0;
        float totalTarjetaFlt=0;
        DecimalFormat formato = new DecimalFormat("#,###.00");
        
        ArrayList<Ventas> unaVenta;
            
          
  
        
        unaVenta=clpdv.buscarTipoVenta();
        
        if(unaVenta==null){
            
        }else{
            for(int i=0;i<unaVenta.size();i++){
                LocalDate fechaHoy= dpFechaHoy.getDate();
                if(fechaHoy.isEqual(unaVenta.get(i).getFechaVenta())){
                    if(unaVenta.get(i).getTipoVenta().equals("CONTADO")){
                        Number nTotalEfectivo = java.text.NumberFormat.getInstance().parse(unaVenta.get(i).getSubTotal());
                        totalContadoFlt= nTotalEfectivo.floatValue();
                        totalContado=totalContado + totalContadoFlt;
                        txtTotalEfectivo.setText(formato.format(totalContado));
                   
                        }else{
                            if(unaVenta.get(i).getTipoVenta().equals("TARJETA")){
                                Number nTotalTarjeta= java.text.NumberFormat.getInstance().parse(unaVenta.get(i).getSubTotal());
                                totalTarjetaFlt=nTotalTarjeta.floatValue();
                                totalTarjeta=totalTarjeta+totalTarjetaFlt;
                                txtTotalTarjeta.setText(formato.format(totalTarjeta));
                            }
                        }
                    }
                }
           
                
            }
        calcularCierreCredito();
        
    }
    public void calcularCierreCredito() throws ParseException{
        float totalCredito=0;
        float totalFlt=0;
        
        DecimalFormat formato = new DecimalFormat("#,###.00");
        ArrayList<Pagos> pagos=new ArrayList<>();
    
    try {
        pagos=clpdv.buscarFechaCierreCredito(dpFechaHoy.getDate());
        
    } catch (PDVException ex) {
        Logger.getLogger(VReportes.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    if (pagos==null){
        
    }else{
  
        for(int i=0;i<pagos.size();i++){
            LocalDate fechaHoy=dpFechaHoy.getDate();
            if(fechaHoy.isEqual(pagos.get(i).getFechaUltPago())){
                Number nTotalCredito= java.text.NumberFormat.getInstance().parse(pagos.get(i).getAbono());
                totalFlt=nTotalCredito.floatValue();
                totalCredito=totalCredito+totalFlt;
                txtTotalCredito.setText(formato.format(totalCredito));
                
            }
         }
       }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private com.github.lgooddatepicker.components.DatePicker dpFechaHoy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtTotalCredito;
    private javax.swing.JTextField txtTotalEfectivo;
    private javax.swing.JTextField txtTotalTarjeta;
    public static javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
