/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Objects.*;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import static java.time.LocalDate.now;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Erick Cordero
 */
public class VCompras extends javax.swing.JFrame {
private Inventario inventario;
private Compras unaCompra;
private ArrayList<Compras> compra;

private Account unaCuenta;
private OpcionesUsuario unUsuario;
private Usuario usuario;

    /**
     * Creates new form VCompras
     */
    public VCompras() {
        initComponents();
        formateaGrid();
        inventario=null;
        unaCompra=null;
        unaCuenta=null;
        unUsuario=null;
        usuario=null;
        clpdv = new CLPDV();
        
        txtSubTotal.setHorizontalAlignment(JTextField.RIGHT);
        txtTotal.setHorizontalAlignment(JTextField.RIGHT);
        txtPagoInicial.setHorizontalAlignment(JTextField.RIGHT);
        txtSaldo.setHorizontalAlignment(JTextField.RIGHT);
        txtPrecioCompra.setHorizontalAlignment(JTextField.RIGHT);
        txtPrecioVenta.setHorizontalAlignment(JTextField.RIGHT);
        
        this.setLocationRelativeTo(null);
        //txtFechaCompra.setText(LocalDate.parse(fechaActual()));
        dpFechaActual.setDateToToday();
        txtIdArticulo.grabFocus();
         if(cboTipoCompra.getSelectedItem().equals("PAGADA")){
            lblPInicial.setVisible(false);
            txtPagoInicial.setVisible(false);
            lblSaldo.setVisible(false);
            txtSaldo.setVisible(false);
            btnCalcularPago.setVisible(false);
         }
        
        if(chkBotonBuscarArtPorNombre.isSelected()){
            btnBuscarPorNombre.setVisible(true);
        }else{
            btnBuscarPorNombre.setVisible(false);
            
        }
        //VBuscarArticuloPorNombre buscarArticulo=new VBuscarArticuloPorNombre();
        //buscarArticulo.setVisible(true);
        
        buscarNoCompra();
       
        
        //try {
            //tableCompras.setModel(clpdv.getComprasTableModel());
       // } catch (PDVException e){
         //   JOptionPane.showMessageDialog(this,e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        //}
    }
     
     public void formateaGrid(){
        tableCompras.getColumnModel().getColumn(0).setPreferredWidth(50);
        tableCompras.getColumnModel().getColumn(1).setPreferredWidth(120);
        tableCompras.getColumnModel().getColumn(2).setPreferredWidth(360);
        tableCompras.getColumnModel().getColumn(3).setPreferredWidth(110);
        tableCompras.getColumnModel().getColumn(4).setPreferredWidth(80);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
   
   public void buscarNoCompra(){
    int idCompra;
         try{
             unaCompra=clpdv.buscarNoCompra();
             idCompra=(unaCompra.getCodCompra()+1);
             txtIdCompra.setText(Integer.toString(idCompra));
             txtIdArticulo.grabFocus();
         }catch (PDVException ex){
             Logger.getLogger(VClientes.class.getName()).log(Level.SEVERE,null, ex);
         }
   }
   public void cerrar(){
       try {
             usuario = clpdv.buscarPorId(txtUsuario.getText());
         } catch (PDVException ex) {
             Logger.getLogger(VInventario.class.getName()).log(Level.SEVERE, null, ex);
         }
        
             if(usuario.getRol().equals("DEPENDIENTE")){
                
                    dispose();
            try {
                unUsuario=clpdv.buscarPorCed(txtUsuario.getText());
            } catch (PDVException ex) {
                Logger.getLogger(VInventario.class.getName()).log(Level.SEVERE, null, ex);
            }
                    if(unUsuario==null){
                        
                    }else{
                         VMenuAdmin menuAdmin=new VMenuAdmin();
                         menuAdmin.setVisible(true);
                         VMenuAdmin.txtUsuario.setText(txtUsuario.getText());
                         if(unUsuario.getCompras().equals("SI")){
                             VMenuAdmin.btnCompras.setEnabled(true);
                        }else{
                             VMenuAdmin.btnCompras.setEnabled(false);
                        }
                        if(unUsuario.getClientes().equals("SI")){
                             VMenuAdmin.btnClientes.setEnabled(true);
                        }else{
                             VMenuAdmin.btnClientes.setEnabled(false);
                        }
                        if(unUsuario.getProveedores().equals("SI")){
                            VMenuAdmin.btnProveedor.setEnabled(true);
                        }else{
                            VMenuAdmin.btnProveedor.setEnabled(false);
                        }
                        if(unUsuario.getInventario().equals("SI")){
                             VMenuAdmin.btnInventario.setEnabled(true);
                        }else{
                             VMenuAdmin.btnInventario.setEnabled(false);
                        }
                        if(unUsuario.getPagos().equals("SI")){
                            VMenuAdmin.btnPagos.setEnabled(true);
                        }else{
                            VMenuAdmin.btnPagos.setEnabled(false);
                        }
                        if(unUsuario.getConsignacion().equals("SI")){
                            VMenuAdmin.btnVentasConsignacion.setEnabled(true);
                        }else{
                            VMenuAdmin.btnVentasConsignacion.setEnabled(false);
                        }
                        if(unUsuario.getReportes().equals("SI")){
                             VMenuAdmin.btnReportes.setEnabled(true);
                        }else{
                             VMenuAdmin.btnReportes.setEnabled(false);
                        }
                        if(unUsuario.getFacturacion().equals("SI")){
                            VMenuAdmin.btnVentas.setEnabled(true);
                        }else{
                            VMenuAdmin.btnVentas.setEnabled(false);
                        }
                    }
             }else{
                 if(usuario.getRol().equals("ADMINISTRADOR")){
                     dispose();
                     VMenuAdmin menu = new VMenuAdmin();
                     menu.setVisible(true);
                     VMenuAdmin.txtUsuario.setText(txtUsuario.getText());
                 }
             }
   }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnBuscar = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCompras = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnAgregarArticulo = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnNuevaCompra = new javax.swing.JButton();
        dpFechaActual = new com.github.lgooddatepicker.components.DatePicker();
        txtId = new javax.swing.JTextField();
        txtIdCompra = new javax.swing.JTextField();
        txtIdArticulo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCantidadActual = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCantidadTotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cboTipoCompra = new javax.swing.JComboBox<>();
        lblPInicial = new javax.swing.JLabel();
        txtPagoInicial = new javax.swing.JTextField();
        lblSaldo = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        btnCalcularPago = new javax.swing.JButton();
        txtArticulo = new javax.swing.JLabel();
        btnBuscarPorNombre = new javax.swing.JButton();
        chkBotonBuscarArtPorNombre = new javax.swing.JCheckBox();
        btnProveedor = new javax.swing.JButton();
        txtProveedor = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNumFactura = new javax.swing.JTextField();
        btnCancelarCompra = new javax.swing.JButton();
        txtPrecioCompra = new javax.swing.JTextField();
        txtPrecioVenta = new javax.swing.JTextField();

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Modulo de Compras");
        setIconImage(getIconImage());
        setMaximumSize(new java.awt.Dimension(1451, 979));
        setMinimumSize(new java.awt.Dimension(1451, 979));
        setPreferredSize(new java.awt.Dimension(1451, 979));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableCompras.setModel(new ComprasTableModel());
        jScrollPane1.setViewportView(tableCompras);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 700, 470));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 720, 490));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        btnAgregarArticulo.setText("Agregar Producto [F4]");
        btnAgregarArticulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAgregarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarArticuloActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir [Escape]");
        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnEliminar.setText("Quitar Producto");
        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnNuevaCompra.setText("Nueva Compra [F2]");
        btnNuevaCompra.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNuevaCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNuevaCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarArticulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addGap(32, 32, 32))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addComponent(btnNuevaCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregarArticulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 37, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 740, 140));

        dpFechaActual.setEnabled(false);
        getContentPane().add(dpFechaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 20, 240, -1));
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 1236, -1, 0));

        txtIdCompra.setEditable(false);
        txtIdCompra.setBackground(new java.awt.Color(153, 255, 153));
        txtIdCompra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtIdCompra.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtIdCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 15, 100, 40));

        txtIdArticulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtIdArticulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtIdArticulo.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtIdArticuloCaretUpdate(evt);
            }
        });
        txtIdArticulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdArticuloFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdArticuloFocusLost(evt);
            }
        });
        txtIdArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdArticuloActionPerformed(evt);
            }
        });
        txtIdArticulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdArticuloKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdArticuloKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdArticuloKeyTyped(evt);
            }
        });
        getContentPane().add(txtIdArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 650, 430, 35));

        jLabel1.setText("No.Compra:");
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 30, 100, 20));

        jLabel4.setText("Artículo:");
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 660, 70, 20));

        jLabel2.setText("Cantidad Actual:");
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 380, 130, 30));

        txtCantidadActual.setEditable(false);
        txtCantidadActual.setBackground(new java.awt.Color(153, 255, 153));
        txtCantidadActual.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCantidadActual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtCantidadActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 380, 130, 30));

        jLabel3.setText("Cantidad Compra:");
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 340, 150, -1));

        txtCantidad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCantidad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantidadKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 340, 100, 30));

        jLabel6.setText("Cantidad Total:");
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 420, 130, 30));

        txtCantidadTotal.setEditable(false);
        txtCantidadTotal.setBackground(new java.awt.Color(153, 255, 153));
        txtCantidadTotal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCantidadTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCantidadTotal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCantidadTotalFocusGained(evt);
            }
        });
        getContentPane().add(txtCantidadTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 420, 130, 30));

        jLabel7.setText("Precio Compra:");
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 460, 120, 20));

        jLabel8.setText("Precio Venta:");
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 500, -1, 30));

        jLabel9.setText("Sub-Total ¢:");
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 540, 100, 30));

        txtSubTotal.setEditable(false);
        txtSubTotal.setBackground(new java.awt.Color(153, 255, 153));
        txtSubTotal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtSubTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 540, 130, 30));

        jLabel10.setText("Total ¢:");
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 580, 70, 30));

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(153, 255, 153));
        txtTotal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 580, 130, 30));

        jLabel11.setText("Proveedor:");
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 300, -1, 20));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de Compra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        cboTipoCompra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PAGADA", "POR PAGAR" }));
        cboTipoCompra.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboTipoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoCompraActionPerformed(evt);
            }
        });

        lblPInicial.setText("Pago Inicial:");
        lblPInicial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtPagoInicial.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPagoInicial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPagoInicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPagoInicialKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPagoInicialKeyReleased(evt);
            }
        });

        lblSaldo.setText("Saldo:");
        lblSaldo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtSaldo.setEditable(false);
        txtSaldo.setBackground(new java.awt.Color(153, 255, 153));
        txtSaldo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtSaldo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoActionPerformed(evt);
            }
        });

        btnCalcularPago.setText("Calcular Saldo");
        btnCalcularPago.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCalcularPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularPagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCalcularPago, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cboTipoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lblPInicial)
                            .addGap(3, 3, 3)
                            .addComponent(txtPagoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(lblSaldo)
                            .addGap(11, 11, 11)
                            .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cboTipoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPInicial)
                    .addComponent(txtPagoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSaldo)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCalcularPago, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 380, 300, 230));

        txtArticulo.setBackground(new java.awt.Color(255, 0, 0));
        txtArticulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtArticulo.setEnabled(false);
        txtArticulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtArticulo.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(txtArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 230, 420, 40));

        btnBuscarPorNombre.setText("...");
        btnBuscarPorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPorNombreActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarPorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 230, 30, -1));

        chkBotonBuscarArtPorNombre.setText("Buscar Artículo por Nombre");
        chkBotonBuscarArtPorNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chkBotonBuscarArtPorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBotonBuscarArtPorNombreActionPerformed(evt);
            }
        });
        getContentPane().add(chkBotonBuscarArtPorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 190, -1, -1));

        btnProveedor.setText("...");
        btnProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(btnProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 290, 30, -1));

        txtProveedor.setBackground(new java.awt.Color(255, 0, 0));
        txtProveedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtProveedor.setEnabled(false);
        txtProveedor.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtProveedor.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(txtProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 290, 420, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Artículo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 240, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("No.Factura Proveedor:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, -1, -1));

        txtNumFactura.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNumFactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumFacturaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumFacturaKeyTyped(evt);
            }
        });
        getContentPane().add(txtNumFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 140, 130, 35));

        btnCancelarCompra.setText("Cancelar Compra");
        btnCancelarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCompraActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, 50));

        txtPrecioCompra.setEditable(false);
        txtPrecioCompra.setBackground(new java.awt.Color(153, 255, 153));
        txtPrecioCompra.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtPrecioCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 460, 130, 30));

        txtPrecioVenta.setEditable(false);
        txtPrecioVenta.setBackground(new java.awt.Color(153, 255, 153));
        txtPrecioVenta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 500, 130, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
       cerrar();
         
        
        
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAgregarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarArticuloActionPerformed
    try {
        // TODO add your handling code here:
        // String nombre = (String) JOptionPane.showInputDialog(this, "Ingrese el nombre del tema",
        //                                                  "Nuevo Tema", JOptionPane.PLAIN_MESSAGE);
        agregarProducto();
    } catch (PDVException ex) {
        Logger.getLogger(VCompras.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_btnAgregarArticuloActionPerformed
    public void agregarProducto()throws PDVException{
        if(txtCantidad.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Debe de indicar cuantos Artículos desea comprar","Atención",JOptionPane.ERROR_MESSAGE);
            txtCantidad.grabFocus();
            
        }else{
             if(txtProveedor.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Debe de indicar el nombre del Proveedor","Atención",JOptionPane.ERROR_MESSAGE);
                txtProveedor.grabFocus();
                
             }else{
                if(txtNumFactura.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Debe de indicar el Número de Factura del Proveedor","Atención",JOptionPane.ERROR_MESSAGE);
                txtNumFactura.grabFocus();
                
             }else{
        
                
        int idCompra= Integer.parseInt(txtIdCompra.getText());
        if ((txtIdArticulo.getText() != null) && (txtIdArticulo.getText().length() > 0)) {
            
            try {
                clpdv.crearCompra(Integer.parseInt(txtIdCompra.getText()),
                                  txtIdArticulo.getText(),
                                  txtArticulo.getText(),
                                  (Integer.parseInt(txtCantidadActual.getText())),
                                  (Integer.parseInt(txtCantidad.getText())),
                                  (Integer.parseInt(txtCantidadTotal.getText())),
                                  txtPrecioCompra.getText(),
                                  txtPrecioVenta.getText(),
                                  txtSubTotal.getText(),
                                  txtTotal.getText(),
                                  txtProveedor.getText(),
                                  dpFechaActual.getDate(),
                                  (String)cboTipoCompra.getSelectedItem(),
                                  txtNumFactura.getText());
                
                clpdv.actualizarInventario(txtIdArticulo.getText(),
                                           (Integer.parseInt(txtCantidadTotal.getText())));
                                 
                                  
                tableCompras.setModel(clpdv.getComprasTableModel(idCompra));
                formateaGrid();
                JOptionPane.showMessageDialog(null,"Agregado correctamente.","Resultado" , JOptionPane.INFORMATION_MESSAGE);
            } 
            catch (PDVException e){
                JOptionPane.showMessageDialog(this,e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        else {
            JOptionPane.showMessageDialog(this,"Datos no insertados", "Información", JOptionPane.WARNING_MESSAGE);
        }
        limpiar();
        }
      }
      }
    }
    public void limpiar(){
        txtIdArticulo.setText("");
        //txtArticulo.setText("");
        txtCantidadActual.setText("");
        txtCantidad.setText("");
        txtCantidadTotal.setText("");
        txtPrecioCompra.setText("");
        txtPrecioVenta.setText("");
        //txtSubTotal.setText("");
        //txtTotal.setText("");
       // txtProveedor.setText("");
        txtIdArticulo.grabFocus();
    }
    public void limpiarDos(){
         lblPInicial.setVisible(false);
        txtPagoInicial.setVisible(false);
        lblSaldo.setVisible(false);
        txtSaldo.setVisible(false);
        btnCalcularPago.setVisible(false);
        cboTipoCompra.setSelectedIndex(0);
        txtSubTotal.setText("");
        txtTotal.setText("");
        buscarNoCompra();
        tableCompras.setModel(new DefaultTableModel());
    }
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
    
    try {
        buscarArticulo();
    } catch (ParseException ex) {
        Logger.getLogger(VCompras.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_btnBuscarActionPerformed
    public void buscarArticulo() throws ParseException{
   
   
    try {
        // TODO add your handling code here:
        inventario = clpdv.buscarArticuloPorCodigo(txtIdArticulo.getText());
    } catch (PDVException ex) {
        Logger.getLogger(VCompras.class.getName()).log(Level.SEVERE, null, ex);
    }
    if(inventario==null){
        //JOptionPane.showMessageDialog(null,"El Articulo Codigo [" + txtIdArticulo.getText() + "] no Existe en el inventario, favor Verificar!!!","Atención",JOptionPane.ERROR_MESSAGE);
        //txtIdArticulo.setText("");
        //txtIdArticulo.grabFocus();
    }else{
        String nombre = inventario.getNombreProducto();
        int cantidad = inventario.getCantidad();
        DecimalFormat formato = new DecimalFormat("#,###.00");
        Number nPrecioCompra = java.text.NumberFormat.getInstance().parse(inventario.getPrecioCompraUnd());
        float precioCompra = nPrecioCompra.floatValue();
        Number nPrecioVenta = java.text.NumberFormat.getInstance().parse(inventario.getPrecioVentaUnd());
        float precioVenta=nPrecioVenta.floatValue();
        txtArticulo.setText(nombre);
        txtCantidadActual.setText(Integer.toString(cantidad));
        txtPrecioCompra.setText(formato.format(precioCompra));
        txtPrecioVenta.setText(formato.format(precioVenta));
        txtProveedor.grabFocus();
        
    }
    
        
    }
    public void restarTotal(float precioCompra) throws ParseException{
        //Procedimiento para restarle del total de la venta en caso de que el usuario
        //haya decidido quitar un producto de la linea de compra
        float totalCompra=0;
       
        DecimalFormat formato = new DecimalFormat("#,###.00");
       
        
        Number nTotalCompra = java.text.NumberFormat.getInstance().parse(txtTotal.getText());
        totalCompra = nTotalCompra.floatValue();
        totalCompra = totalCompra-precioCompra;
        txtTotal.setText(formato.format(totalCompra));
       
        
       
    }
    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
         //cantidadTotal();
        
        
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isLetter(c)) {
              getToolkit().beep();
              evt.consume();
              
              JOptionPane.showMessageDialog(null,"No puede ingresar letras!!!,","Error",JOptionPane.ERROR_MESSAGE);
        }     
        
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void txtCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyPressed
        // TODO add your handling code here:
        if(KeyEvent.getKeyText(evt.getKeyCode()).equals("F4")){
                try {
                    agregarProducto();
                } catch (PDVException ex) {
                    Logger.getLogger(VVentas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
            if(KeyEvent.getKeyText(evt.getKeyCode()).equals("Escape")){
                 cerrar();
            }
                }
      
    }//GEN-LAST:event_txtCantidadKeyPressed

    private void txtCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyReleased
    if (txtCantidad.getText().length()>=1) {
        try {
        // TODO add your handling code here:
        cantidadTotal();
        } catch (ParseException ex) {
              Logger.getLogger(VCompras.class.getName()).log(Level.SEVERE, null, ex);
        } catch (PDVException ex) {
            Logger.getLogger(VCompras.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    }//GEN-LAST:event_txtCantidadKeyReleased

    private void txtIdArticuloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdArticuloKeyReleased
    try {
        // TODO add your handling code here:
        buscarArticulo();
    } catch (ParseException ex) {
        Logger.getLogger(VCompras.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_txtIdArticuloKeyReleased

    private void txtIdArticuloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdArticuloKeyTyped
        // TODO add your handling code here:
         char charecter = evt.getKeyChar();
        if (Character.isLowerCase(charecter)) {
            evt.setKeyChar(Character.toUpperCase(charecter));
        }
        
    }//GEN-LAST:event_txtIdArticuloKeyTyped

    
    private void txtIdArticuloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdArticuloKeyPressed
        // TODO add your handling code here:
        if(KeyEvent.getKeyText(evt.getKeyCode()).equals("F2")){
                try {
                    agregarProducto();
                } catch (PDVException ex) {
                    Logger.getLogger(VVentas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
            if(KeyEvent.getKeyText(evt.getKeyCode()).equals("Escape")){
                 cerrar();
             }
           }
       
    }//GEN-LAST:event_txtIdArticuloKeyPressed
 
    private void txtIdArticuloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdArticuloFocusLost
    try {
        // TODO add your handling code here:
        buscarArticulo();
    } catch (ParseException ex) {
        Logger.getLogger(VCompras.class.getName()).log(Level.SEVERE, null, ex);
    }
         
    }//GEN-LAST:event_txtIdArticuloFocusLost
    
    private void txtIdArticuloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdArticuloFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtIdArticuloFocusGained

    private void txtIdArticuloCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtIdArticuloCaretUpdate
        // TODO add your handling code here:
       
         
    }//GEN-LAST:event_txtIdArticuloCaretUpdate

    private void txtIdArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdArticuloActionPerformed
        // TODO add your handling code here:
        //buscarArticulo();
    }//GEN-LAST:event_txtIdArticuloActionPerformed

    private void txtCantidadTotalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidadTotalFocusGained
      
    }//GEN-LAST:event_txtCantidadTotalFocusGained

    private void btnBuscarPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPorNombreActionPerformed
  
      
      VBuscarArticuloPorNombre buscarArticulo=new VBuscarArticuloPorNombre();
      buscarArticulo.setVisible(true);
      VBuscarArticuloPorNombre.txtTipoTransaccion.setText("COMPRAS");
   
   
    }//GEN-LAST:event_btnBuscarPorNombreActionPerformed
    
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
       int codCompra = Integer.parseInt(txtIdCompra.getText());
       float precioCompra=0;
       
       //int cantTotal = Integer.parseInt(txtCantidadTotal.getText());
        try {
            int row = tableCompras.getSelectedRow();
            if (row > -1){
                ComprasTableModel ctm = (ComprasTableModel)tableCompras.getModel();
                
                //int cantidadAgregada= ctm.getCompras(row).getAgregarCantidad();
                clpdv.eliminarCompras(ctm.getCompras(row),codCompra);
                
                tableCompras.setModel(clpdv.getComprasTableModel(codCompra));
                inventario=clpdv.buscarArticuloPorCodigo(ctm.getCompras(row).getIdArticulo());
                 //se saca el precio de venta de la linea del producto que el usuario está eliminando de la compra
                Number nPrecioCompra = java.text.NumberFormat.getInstance().parse(ctm.getCompras(row).getSubTotal());
                precioCompra=nPrecioCompra.floatValue();
                //se envía al procedimiento restarTotal, el monto del precio de la venta del producto que se está quitando
                //de la compra, para que pueda ser restado del total de la venta.
                restarTotal(precioCompra);
                int cantTotal= inventario.getCantidad();
                clpdv.descontarArticuloDeInventario(ctm.getCompras(row).getIdArticulo(),
                                           (ctm.getCompras(row).getAgregarCantidad()),
                                           (cantTotal));
                JOptionPane.showMessageDialog(this,"Eliminado correctamente.","Resultado" , JOptionPane.INFORMATION_MESSAGE);
            }
            else
            JOptionPane.showMessageDialog(this,"Seleccione el Artículo a Eliminar", "Información", JOptionPane.WARNING_MESSAGE);
        } catch (PDVException e){
            JOptionPane.showMessageDialog(this,e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (ParseException ex) {
        Logger.getLogger(VCompras.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void cboTipoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoCompraActionPerformed
        // TODO add your handling code here:
          // TODO add your handling code here:
        if(cboTipoCompra.getSelectedItem().equals("PAGADA")){
            lblPInicial.setVisible(false);
            txtPagoInicial.setVisible(false);
            lblSaldo.setVisible(false);
            txtSaldo.setVisible(false);
            btnCalcularPago.setVisible(false);
            txtArticulo.grabFocus();
        }else{
            if(cboTipoCompra.getSelectedItem().equals("POR PAGAR")){
                lblPInicial.setVisible(true);
                txtPagoInicial.setVisible(true);
                lblSaldo.setVisible(true);
                txtSaldo.setVisible(true);
                btnCalcularPago.setVisible(true);
                txtPagoInicial.requestFocus();
                if(txtPagoInicial.getText().equals("")){
                    
                    txtSaldo.setText(txtTotal.getText());
                }
                    
                
                
                
            }
            
        }
    }//GEN-LAST:event_cboTipoCompraActionPerformed

    private void txtSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoActionPerformed

    private void txtPagoInicialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPagoInicialKeyReleased
   
    }//GEN-LAST:event_txtPagoInicialKeyReleased

    private void btnCalcularPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularPagoActionPerformed
    try {
        // TODO add your handling code here:
        calcularTotalCompra();
    } catch (PDVException ex) {
        Logger.getLogger(VCompras.class.getName()).log(Level.SEVERE, null, ex);
    } catch (ParseException ex) {
        Logger.getLogger(VCompras.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_btnCalcularPagoActionPerformed

    private void btnNuevaCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaCompraActionPerformed
        // TODO add your handling code here:
       limpiarDos();
       txtNumFactura.setText("");
               
    }//GEN-LAST:event_btnNuevaCompraActionPerformed

    private void chkBotonBuscarArtPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBotonBuscarArtPorNombreActionPerformed
        // TODO add your handling code here:
          if(chkBotonBuscarArtPorNombre.isSelected()){
            btnBuscarPorNombre.setVisible(true);
        }else{
            btnBuscarPorNombre.setVisible(false);
            
        }
    }//GEN-LAST:event_chkBotonBuscarArtPorNombreActionPerformed

    private void txtPagoInicialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPagoInicialKeyPressed
        // TODO add your handling code here:
               if(KeyEvent.getKeyText(evt.getKeyCode()).equals("Escape")){
                cerrar();
               }
                
    }//GEN-LAST:event_txtPagoInicialKeyPressed

    private void btnProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedorActionPerformed
        // TODO add your handling code here:
                
    try {
        VModalBuscarProveedor buscarProveedor;
        buscarProveedor = new VModalBuscarProveedor();
        buscarProveedor.setVisible(true);
    } catch (PDVException ex) {
        Logger.getLogger(VCompras.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_btnProveedorActionPerformed

    private void txtNumFacturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumFacturaKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isLetter(c)) {
              getToolkit().beep();
              evt.consume();
              
              JOptionPane.showMessageDialog(null,"No puede ingresar letras!!!,","Error",JOptionPane.ERROR_MESSAGE);
        }     
        
    }//GEN-LAST:event_txtNumFacturaKeyTyped

    private void txtNumFacturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumFacturaKeyPressed
        // TODO add your handling code here:
        if(KeyEvent.getKeyText(evt.getKeyCode()).equals("Escape")){
                 cerrar();
            }
        
    }//GEN-LAST:event_txtNumFacturaKeyPressed

    private void btnCancelarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCompraActionPerformed
        // TODO add your handling code here:
        int codCompra=Integer.parseInt(txtIdCompra.getText());
        
    try {
        clpdv.cancelarCompra(codCompra);
        JOptionPane.showMessageDialog(null,"Compra Cancelada Satisfactoriamente","Atención",JOptionPane.INFORMATION_MESSAGE);
        tableCompras.setModel(clpdv.getComprasTableModel(codCompra));
        txtIdArticulo.grabFocus();
    } catch (PDVException ex) {
        Logger.getLogger(VCompras.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_btnCancelarCompraActionPerformed

    public void calcularTotalCompra()throws PDVException, ParseException{
        float abono;
        float saldo;
        float total;
       
        if(txtPagoInicial.getText().equals("")){
            txtSaldo.setText(txtTotal.getText());
        }else{
            DecimalFormat formato = new DecimalFormat("#,###.00");
            Number nAbono = java.text.NumberFormat.getInstance().parse(txtPagoInicial.getText());
            abono=nAbono.floatValue();
            Number nSaldo = java.text.NumberFormat.getInstance().parse(txtSaldo.getText());
            saldo=nSaldo.floatValue();
            Number nTotal = java.text.NumberFormat.getInstance().parse(txtTotal.getText());
            total=nTotal.floatValue();
            if(abono>total){
                JOptionPane.showMessageDialog(null,"El Pago Inicial no puede ser mayor al total de la deuda","Atención",JOptionPane.ERROR_MESSAGE);
                txtPagoInicial.setText("");
                txtPagoInicial.requestFocus();
                
            }else{
                saldo= total-abono;
                txtSaldo.setText(formato.format(saldo));
                try {
                    actualizarTotalCompra();
                } catch (PDVException ex) {
                    Logger.getLogger(VCompras.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
                          
        
    }
    public void actualizarTotalCompra()throws PDVException{
        
        DecimalFormat formato = new DecimalFormat("#,###.00");
        try{
            int codCompra=Integer.parseInt(txtIdCompra.getText());
            String codArt=txtId.getText();
            //Number nSaldo = java.text.NumberFormat.getInstance().parse(txtTotal.getText());
            //float saldo=nSaldo.floatValue();
            String tipoCompra=(String) cboTipoCompra.getSelectedItem();
            
            
            clpdv.actualizarTotalCompra(codCompra,codArt,txtTotal.getText(),tipoCompra);
            JOptionPane.showMessageDialog(null,"Compra registrada satisfactoriamente ","Atención",JOptionPane.INFORMATION_MESSAGE);
            lblPInicial.setVisible(false);
            txtPagoInicial.setVisible(false);
            lblSaldo.setVisible(false);
            txtSaldo.setVisible(false);
            btnCalcularPago.setVisible(false);
            cboTipoCompra.setSelectedIndex(0);
            txtSubTotal.setText("");
            txtTotal.setText("");
            txtProveedor.setText("");
            buscarNoCompra();
            tableCompras.setModel(new DefaultTableModel());
                    
        }catch (PDVException ex){
                Logger.getLogger(VClientes.class.getName()).log(Level.SEVERE,null, ex);
        }
                
    }
    public void cantidadTotal() throws ParseException, PDVException{
        int cantidadTotal;
        int cantidadActual;
        int agregar;
       if(txtCantidad.getText().equals("")){
          txtCantidadTotal.setText("");
       }else{
         agregar = Integer.parseInt(txtCantidad.getText());
         cantidadActual= Integer.parseInt(txtCantidadActual.getText());
         cantidadTotal= cantidadActual+agregar;
         txtCantidadTotal.setText(Integer.toString(cantidadTotal));
         subTotal();  
       }
        
        
    }
    public void subTotal() throws ParseException, PDVException{
       
        int cantidad;
        float precioCompra;
        float preTotal=0;
        float totalCompra=0;
        DecimalFormat formato = new DecimalFormat("#,###.00");
        
            
            cantidad = Integer.parseInt((txtCantidad.getText()));
            Number nPrecioCompra = java.text.NumberFormat.getInstance().parse(txtPrecioCompra.getText());
            precioCompra = nPrecioCompra.floatValue();
            preTotal= (cantidad*precioCompra);
                
            txtSubTotal.setText(formato.format(preTotal));
            // txtSubTotal.setText(Double.toString(subT));
           if(txtTotal.getText().equals("")){
               txtTotal.setText(Float.toString(0));
               totalCompra= totalCompra + preTotal;
               txtTotal.setText(formato.format(totalCompra));
           }else{
               if(txtId.getText().equals(txtIdArticulo.getText())){
                txtTotal.setText(txtSubTotal.getText());
               }else{
                   Number nTotal = java.text.NumberFormat.getInstance().parse(txtTotal.getText());
                   totalCompra=nTotal.floatValue();
                   totalCompra= totalCompra + preTotal;
                   txtTotal.setText(formato.format(totalCompra));
               }
           }
           
           
           txtId.setText(txtIdArticulo.getText());
           //agregarProducto();
           
    }
    
    public Date fechaActual(){
        Date fecha=new Date();
        //SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/YYY");
        return (fecha);
        
    }
    /**
     * @param args the command line arguments
     */
    private CLPDV clpdv;
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VCompras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarArticulo;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarPorNombre;
    private javax.swing.JButton btnCalcularPago;
    private javax.swing.JButton btnCancelarCompra;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevaCompra;
    private javax.swing.JButton btnProveedor;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboTipoCompra;
    private javax.swing.JCheckBox chkBotonBuscarArtPorNombre;
    private com.github.lgooddatepicker.components.DatePicker dpFechaActual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPInicial;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JTable tableCompras;
    public static javax.swing.JLabel txtArticulo;
    public static javax.swing.JTextField txtCantidad;
    public static javax.swing.JTextField txtCantidadActual;
    private javax.swing.JTextField txtCantidadTotal;
    private javax.swing.JTextField txtId;
    public static javax.swing.JTextField txtIdArticulo;
    private javax.swing.JTextField txtIdCompra;
    private javax.swing.JTextField txtNumFactura;
    private javax.swing.JTextField txtPagoInicial;
    public static javax.swing.JTextField txtPrecioCompra;
    public static javax.swing.JTextField txtPrecioVenta;
    public static javax.swing.JLabel txtProveedor;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTotal;
    public static javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
