/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Multi.*;
import Objects.*;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author Erick Cordero   
 */
public class VentanaRegistroAdmin extends javax.swing.JFrame {
    
    private Usuario usuario;

    /**
     * Creates new form VentanaRegistroAdmin
     */
    public VentanaRegistroAdmin() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        usuario=null;
        clpdv = new CLPDV();
        TxtId.grabFocus();
         if(cboRol.getSelectedItem().equals("ADMINISTRADOR")){
            jpnOpcionesUsuario.setVisible(false);
            
        }else{
            if(cboRol.getSelectedItem().equals("DEPENDIENTE")){
                jpnOpcionesUsuario.setVisible(true);
            }
        }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Campos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TxtId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtApellidos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TxtDireccion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TxtEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cboRol = new javax.swing.JComboBox<>();
        dpFechaNacimiento = new com.github.lgooddatepicker.components.DatePicker();
        jpnOpcionesUsuario = new javax.swing.JPanel();
        chkCompras = new javax.swing.JCheckBox();
        chkClientes = new javax.swing.JCheckBox();
        chkProveedores = new javax.swing.JCheckBox();
        chkInventario = new javax.swing.JCheckBox();
        chkReportes = new javax.swing.JCheckBox();
        chkFacturacion = new javax.swing.JCheckBox();
        chkPagos = new javax.swing.JCheckBox();
        chkConsignacion = new javax.swing.JCheckBox();
        panel_Opciones = new javax.swing.JPanel();
        btn_RegistrarAdmin = new javax.swing.JButton();
        btn_Cerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconImage(getIconImage());
        setMaximumSize(new java.awt.Dimension(850, 700));
        setMinimumSize(new java.awt.Dimension(850, 700));
        setPreferredSize(new java.awt.Dimension(850, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_Campos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro Administrador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel2.setText("Identificacion:");
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        TxtId.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TxtId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TxtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIdActionPerformed(evt);
            }
        });
        TxtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtIdKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtIdKeyTyped(evt);
            }
        });

        jLabel3.setText("Nombre:");
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        TxtNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TxtNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreActionPerformed(evt);
            }
        });
        TxtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNombreKeyTyped(evt);
            }
        });

        jLabel4.setText("Apellidos:");
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        TxtApellidos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TxtApellidos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TxtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtApellidosActionPerformed(evt);
            }
        });
        TxtApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtApellidosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtApellidosKeyTyped(evt);
            }
        });

        jLabel5.setText("Telefono:");
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        TxtTelefono.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TxtTelefono.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TxtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTelefonoActionPerformed(evt);
            }
        });
        TxtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtTelefonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtTelefonoKeyTyped(evt);
            }
        });

        jLabel6.setText("Rol:");
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel7.setText("Direccion:");
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        TxtDireccion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TxtDireccion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TxtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDireccionActionPerformed(evt);
            }
        });
        TxtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtDireccionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtDireccionKeyTyped(evt);
            }
        });

        jLabel8.setText("E-mail:");
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        TxtEmail.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TxtEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TxtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEmailActionPerformed(evt);
            }
        });
        TxtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtEmailKeyPressed(evt);
            }
        });

        jLabel9.setText("Fecha de Nacimiento:");
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        cboRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMINISTRADOR", "DEPENDIENTE" }));
        cboRol.setBackground(new java.awt.Color(153, 255, 153));
        cboRol.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cboRol.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cboRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboRolActionPerformed(evt);
            }
        });
        cboRol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboRolKeyPressed(evt);
            }
        });

        dpFechaNacimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dpFechaNacimientoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panel_CamposLayout = new javax.swing.GroupLayout(panel_Campos);
        panel_Campos.setLayout(panel_CamposLayout);
        panel_CamposLayout.setHorizontalGroup(
            panel_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_CamposLayout.createSequentialGroup()
                .addGroup(panel_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_CamposLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(panel_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(dpFechaNacimiento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                .addComponent(TxtEmail, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(panel_CamposLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(panel_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                            .addComponent(TxtId)
                            .addComponent(TxtApellidos)
                            .addComponent(TxtTelefono)
                            .addComponent(cboRol, 0, 219, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_CamposLayout.setVerticalGroup(
            panel_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_CamposLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panel_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(panel_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(panel_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(cboRol, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(panel_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TxtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(panel_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(dpFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(panel_Campos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 800, 390));

        jpnOpcionesUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opiones a asignar al usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        chkCompras.setText("Ingresar Compras");

        chkClientes.setText("Ingresar Clientes");

        chkProveedores.setText("Ingresar Proveedores");

        chkInventario.setText("Ingresar Artículos al Inventario");

        chkReportes.setText("Reportes");

        chkFacturacion.setText("Facturación");
        chkFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFacturacionActionPerformed(evt);
            }
        });

        chkPagos.setText("Pagos");

        chkConsignacion.setText("Ventas a Consignación");

        javax.swing.GroupLayout jpnOpcionesUsuarioLayout = new javax.swing.GroupLayout(jpnOpcionesUsuario);
        jpnOpcionesUsuario.setLayout(jpnOpcionesUsuarioLayout);
        jpnOpcionesUsuarioLayout.setHorizontalGroup(
            jpnOpcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnOpcionesUsuarioLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jpnOpcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkClientes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnOpcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkPagos)
                    .addComponent(chkInventario))
                .addGap(12, 12, 12)
                .addGroup(jpnOpcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnOpcionesUsuarioLayout.createSequentialGroup()
                        .addComponent(chkConsignacion)
                        .addGap(18, 18, 18)
                        .addComponent(chkFacturacion))
                    .addGroup(jpnOpcionesUsuarioLayout.createSequentialGroup()
                        .addComponent(chkProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jpnOpcionesUsuarioLayout.setVerticalGroup(
            jpnOpcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnOpcionesUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnOpcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCompras)
                    .addComponent(chkPagos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnOpcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkClientes)
                    .addComponent(chkInventario)
                    .addComponent(chkConsignacion)
                    .addComponent(chkFacturacion))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(jpnOpcionesUsuarioLayout.createSequentialGroup()
                .addGroup(jpnOpcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkProveedores)
                    .addComponent(chkReportes))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jpnOpcionesUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 800, 100));

        panel_Opciones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        btn_RegistrarAdmin.setText("Guardar");
        btn_RegistrarAdmin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_RegistrarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegistrarAdminActionPerformed(evt);
            }
        });

        btn_Cerrar.setText("Cerrar");
        btn_Cerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_OpcionesLayout = new javax.swing.GroupLayout(panel_Opciones);
        panel_Opciones.setLayout(panel_OpcionesLayout);
        panel_OpcionesLayout.setHorizontalGroup(
            panel_OpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_OpcionesLayout.createSequentialGroup()
                .addContainerGap(216, Short.MAX_VALUE)
                .addComponent(btn_RegistrarAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184)
                .addComponent(btn_Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );
        panel_OpcionesLayout.setVerticalGroup(
            panel_OpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_OpcionesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panel_OpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_RegistrarAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(panel_Opciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 800, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIdActionPerformed
        // TODO add your handling code here:
        evt.setSource((char) KeyEvent.VK_CLEAR);
        TxtNombre.requestFocus();// al presionar enter mandas el cursor a jTextField2
    }//GEN-LAST:event_TxtIdActionPerformed

    private void TxtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtIdKeyTyped
        // TODO add your handling code here:

        /*int k=(int)evt.getKeyChar();
        if (k >= 97 && k <= 122 || k>=65 && k<=90){
            evt.setKeyChar((char)KeyEvent.VK_CLEAR);
            JOptionPane.showMessageDialog(null,"No puede ingresar letras!!!","Ventana Error Datos",JOptionPane.ERROR_MESSAGE);
        }
        if(k==241 || k==209){
            evt.setKeyChar((char)KeyEvent.VK_CLEAR);
            JOptionPane.showMessageDialog(null,"No puede ingresar letras!!!","Ventana Error Datos",JOptionPane.ERROR_MESSAGE);
        }*/
        char c=evt.getKeyChar();

        if(Character.isLetter(c)) {
            getToolkit().beep();

            evt.consume();

            JOptionPane.showMessageDialog(null,"No puede ingresar letras!!!,El Usuario es su Número de Cédula","Error",JOptionPane.ERROR_MESSAGE);

        }
        
        if (TxtId.getText().length()>=9) {
            getToolkit().beep();
            evt.consume();
        }
        

    }//GEN-LAST:event_TxtIdKeyTyped

    private void TxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreActionPerformed
        // TODO add your handling code here:
        evt.setSource((char) KeyEvent.VK_CLEAR);
        TxtApellidos.requestFocus();// al presionar enter mandas el cursor a jTextField2

    }//GEN-LAST:event_TxtNombreActionPerformed

    private void TxtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNombreKeyTyped
        // TODO add your handling code here:
        // TODO add your handling code here:
        char charecter = evt.getKeyChar();
        if (Character.isLowerCase(charecter)) {
            evt.setKeyChar(Character.toUpperCase(charecter));
        }

    }//GEN-LAST:event_TxtNombreKeyTyped

    private void TxtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtApellidosActionPerformed
        // TODO add your handling code here:
        evt.setSource((char) KeyEvent.VK_CLEAR);
        TxtTelefono.requestFocus();// al presionar enter mandas el cursor a jTextField2
    }//GEN-LAST:event_TxtApellidosActionPerformed

    private void TxtApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtApellidosKeyTyped
        // TODO add your handling code here:
        char charecter = evt.getKeyChar();
        if (Character.isLowerCase(charecter)) {
            evt.setKeyChar(Character.toUpperCase(charecter));
        }
    }//GEN-LAST:event_TxtApellidosKeyTyped

    private void TxtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTelefonoActionPerformed
        // TODO add your handling code here:
        evt.setSource((char) KeyEvent.VK_CLEAR);
        TxtDireccion.requestFocus();// al presionar enter mandas el cursor a jTextField2
    }//GEN-LAST:event_TxtTelefonoActionPerformed

    private void TxtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTelefonoKeyTyped
        // TODO add your handling code here:
       char c=evt.getKeyChar();

        if(Character.isLetter(c)) {
            getToolkit().beep();

            evt.consume();

            JOptionPane.showMessageDialog(null,"No puede ingresar letras!!!,El Usuario es su Número de Cédula","Error",JOptionPane.ERROR_MESSAGE);

        }
        
        if (TxtTelefono.getText().length()>=8) {
            getToolkit().beep();
            evt.consume();
        }
        
        
    }//GEN-LAST:event_TxtTelefonoKeyTyped

    private void TxtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDireccionActionPerformed
        // TODO add your handling code here:
        evt.setSource((char) KeyEvent.VK_CLEAR);
        TxtEmail.requestFocus();// al presionar enter mandas el cursor a jTextField2
    }//GEN-LAST:event_TxtDireccionActionPerformed

    private void TxtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDireccionKeyTyped
        // TODO add your handling code here:
        char charecter = evt.getKeyChar();
        if (Character.isLowerCase(charecter)) {
            evt.setKeyChar(Character.toUpperCase(charecter));
        }
    }//GEN-LAST:event_TxtDireccionKeyTyped

    private void TxtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEmailActionPerformed
        // TODO add your handling code here:
        evt.setSource((char) KeyEvent.VK_CLEAR);
        dpFechaNacimiento.requestFocus();// al presionar enter mandas el cursor a jTextField2
    }//GEN-LAST:event_TxtEmailActionPerformed

    private void btn_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_CerrarActionPerformed

    private void btn_RegistrarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegistrarAdminActionPerformed
        
        // TODO add your handling code here:
        if(usuario==null)
        {
            crearUsuario();
        }
    }
        
        public void crearUsuario(){
            
         //MultiUsuario multiUsuario = new MultiUsuario();
        
        try{
            //txtFNac.setFormatterFactory(new DefaultFormatterFactory(new MaskFormatter("##/##/####")));
            //DateTimeFormatter sdf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            //LocalDate fechaNac = LocalDate.parse(txtFNac.getText(),sdf);
         
            usuario=clpdv.buscarPorId(TxtId.getText());
            if(usuario==null){
            clpdv.crearUsuario(TxtId.getText() ,
                               TxtNombre.getText() ,
                               TxtApellidos.getText(),
                               TxtTelefono.getText(), 
                               (String) cboRol.getSelectedItem(),
                               TxtDireccion.getText(), 
                               TxtEmail.getText(),
                               dpFechaNacimiento.getDate());
            if(cboRol.getSelectedItem().equals("DEPENDIENTE")){
                String compras="";
                String clientes="";
                String proveedores="";
                String inventario="";
                String pagos="";
                String consignacion="";
                String reportes="";
                String facturacion="";
                
                if(chkCompras.isSelected()){
                    compras="SI";
                }else{
                    compras="NO";
                }
                if(chkClientes.isSelected()){
                    clientes="SI";
                }else{
                    clientes="NO";
                }
                if(chkProveedores.isSelected()){
                    proveedores="SI";
                }else{
                    proveedores="NO";
                }
                if(chkInventario.isSelected()){
                    inventario="SI";
                }else{
                    inventario="NO";
                }
                if(chkPagos.isSelected()){
                    pagos="SI";
                }else{
                    pagos="NO";
                }
                if(chkConsignacion.isSelected()){
                    consignacion="SI";
                }else{
                    consignacion="NO";
                }
                if(chkReportes.isSelected()){
                    reportes="SI";
                }else{
                    reportes="NO";
                }
                if(chkFacturacion.isSelected()){
                    facturacion="SI";
                }else{
                    facturacion="NO";
                }
                
                clpdv.crearOpcionesUsuario(TxtId.getText(),
                                           compras,
                                           clientes,
                                           proveedores,
                                           inventario,
                                           pagos,
                                           consignacion,
                                           reportes,
                                           facturacion);
                        
            }
            JOptionPane.showMessageDialog(null,"Usuario creado Satisfactoriamente!!,Proceda a registrar una Clave","Atención!!",JOptionPane.INFORMATION_MESSAGE);
            
            VentanaCuenta cuenta= new VentanaCuenta();
            cuenta.setVisible(true);
            cuenta.txtUser.setText(TxtId.getText());
            cuenta.txtUser.setEnabled(true);
            cuenta.txtUser.setEditable(false);
            cuenta.txtUser.setBounds(WIDTH, WIDTH, 150, 25);
            cuenta.txtPassword.setBounds(WIDTH, WIDTH, 150, 25);
            cuenta.lblConfirm.setVisible(false);
            cuenta.txtPassConfirm.setVisible(false);
            //Limpia los campos
            TxtId.setText("");
            TxtNombre.setText("");
            TxtApellidos.setText("");
            TxtTelefono.setText("");
            cboRol.setSelectedIndex(0);
            TxtDireccion.setText("");
            TxtEmail.setText("");
            dpFechaNacimiento.setText("");
            dispose();
            }else{
                JOptionPane.showMessageDialog(null,"El usuario " + TxtId.getText() + " Ya existe, Favor verificar!!!","Atención!!!",JOptionPane.ERROR_MESSAGE);
                TxtId.setText("");
                TxtId.grabFocus();
            }
        }catch (java.lang.Exception e){
            System.out.println(e.getMessage());
        }
    

        
                                        
    }//GEN-LAST:event_btn_RegistrarAdminActionPerformed

    private void cboRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboRolActionPerformed
        // TODO add your handling code here:
        if(cboRol.getSelectedItem().equals("ADMINISTRADOR")){
            jpnOpcionesUsuario.setVisible(false);
            
        }else{
            if(cboRol.getSelectedItem().equals("DEPENDIENTE")){
                jpnOpcionesUsuario.setVisible(true);
            }
        }
    }//GEN-LAST:event_cboRolActionPerformed

    private void TxtIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtIdKeyPressed
        // TODO add your handling code here:
        if(KeyEvent.getKeyText(evt.getKeyCode()).equals("Escape")){
            dispose();
            
         }
    }//GEN-LAST:event_TxtIdKeyPressed

    private void TxtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNombreKeyPressed
        // TODO add your handling code here:
        if(KeyEvent.getKeyText(evt.getKeyCode()).equals("Escape")){
            dispose();
           
         }
    }//GEN-LAST:event_TxtNombreKeyPressed

    private void TxtApellidosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtApellidosKeyPressed
        // TODO add your handling code here:
        if(KeyEvent.getKeyText(evt.getKeyCode()).equals("Escape")){
            dispose();
           
         }
    }//GEN-LAST:event_TxtApellidosKeyPressed

    private void TxtTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTelefonoKeyPressed
        // TODO add your handling code here:
        if(KeyEvent.getKeyText(evt.getKeyCode()).equals("Escape")){
            dispose();
            
         }
    }//GEN-LAST:event_TxtTelefonoKeyPressed

    private void cboRolKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboRolKeyPressed
        // TODO add your handling code here:
        if(KeyEvent.getKeyText(evt.getKeyCode()).equals("Escape")){
            dispose();
           
         }
    }//GEN-LAST:event_cboRolKeyPressed

    private void TxtDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDireccionKeyPressed
        // TODO add your handling code here:
        if(KeyEvent.getKeyText(evt.getKeyCode()).equals("Escape")){
            dispose();
           
         }
    }//GEN-LAST:event_TxtDireccionKeyPressed

    private void TxtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtEmailKeyPressed
        // TODO add your handling code here:
        if(KeyEvent.getKeyText(evt.getKeyCode()).equals("Escape")){
            dispose();
            
         }
    }//GEN-LAST:event_TxtEmailKeyPressed

    private void dpFechaNacimientoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dpFechaNacimientoKeyPressed
        // TODO add your handling code here:
        if(KeyEvent.getKeyText(evt.getKeyCode()).equals("Escape")){
            dispose();
            
         }
    }//GEN-LAST:event_dpFechaNacimientoKeyPressed

    private void chkFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFacturacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkFacturacionActionPerformed

    /**
     * @param args the command line arguments
     */
    private CLPDV clpdv;
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegistroAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtApellidos;
    private javax.swing.JTextField TxtDireccion;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtId;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtTelefono;
    private javax.swing.JButton btn_Cerrar;
    private javax.swing.JButton btn_RegistrarAdmin;
    private javax.swing.JComboBox<String> cboRol;
    private javax.swing.JCheckBox chkClientes;
    private javax.swing.JCheckBox chkCompras;
    private javax.swing.JCheckBox chkConsignacion;
    private javax.swing.JCheckBox chkFacturacion;
    private javax.swing.JCheckBox chkInventario;
    private javax.swing.JCheckBox chkPagos;
    private javax.swing.JCheckBox chkProveedores;
    private javax.swing.JCheckBox chkReportes;
    private com.github.lgooddatepicker.components.DatePicker dpFechaNacimiento;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jpnOpcionesUsuario;
    private javax.swing.JPanel panel_Campos;
    private javax.swing.JPanel panel_Opciones;
    // End of variables declaration//GEN-END:variables
}
