/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Objects.*;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.text.DecimalFormat;
import java.text.NumberFormat;

/**
 *
 * @author Erick Cordero
 */
public class VInventario extends javax.swing.JFrame {
     private Inventario inventario;
     private Account unaCuenta;
     private OpcionesUsuario unUsuario;
     private Usuario usuario;
    /**
     * Creates new form VInventario
     */
    public VInventario() {
        initComponents();
        inventario=null;
        unaCuenta=null;
        unUsuario=null;
        usuario=null;
        clpdv=new CLPDV();
        this.setLocationRelativeTo(null);
        txtIdArticulo.grabFocus();
        
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsuario = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIdArticulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNomArticulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btoUnidad = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtPrecioCompra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPrecioVenta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPorcUtilidad = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        spCantidad = new javax.swing.JSpinner();
        spCantidadReserva = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Inventario");
        setIconImage(getIconImage());
        setMaximumSize(new java.awt.Dimension(1451, 979));
        setMinimumSize(new java.awt.Dimension(1451, 979));
        setName("Inventario"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1451, 979));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agregar Articulos al Inventario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel1.setText("Codigo Articulo:");

        txtIdArticulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtIdArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdArticuloActionPerformed(evt);
            }
        });
        txtIdArticulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdArticuloKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdArticuloKeyTyped(evt);
            }
        });

        jLabel2.setText("Nombre:");

        txtNomArticulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNomArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomArticuloActionPerformed(evt);
            }
        });
        txtNomArticulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomArticuloKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomArticuloKeyTyped(evt);
            }
        });

        jLabel4.setText("Cantidad:");

        jLabel5.setText("Unidad:");

        btoUnidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GRAMO", "KILOGRAMO", "LITRO", "METRO", "METRO CUBICO", "PIEZA", "OTRO" }));
        btoUnidad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btoUnidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btoUnidadKeyPressed(evt);
            }
        });

        jLabel3.setText("Precio Compra Unidad:");

        txtPrecioCompra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPrecioCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioCompraActionPerformed(evt);
            }
        });
        txtPrecioCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrecioCompraKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioCompraKeyTyped(evt);
            }
        });

        jLabel6.setText("Precio Venta Unidad:");

        txtPrecioVenta.setEditable(false);
        txtPrecioVenta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPrecioVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioVentaActionPerformed(evt);
            }
        });
        txtPrecioVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrecioVentaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioVentaKeyTyped(evt);
            }
        });

        jLabel7.setText("Cantidad Reserva:");

        jLabel8.setText("% Utilidad");

        txtPorcUtilidad.setBackground(new java.awt.Color(153, 255, 153));
        txtPorcUtilidad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPorcUtilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPorcUtilidadActionPerformed(evt);
            }
        });
        txtPorcUtilidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPorcUtilidadKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPorcUtilidadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPorcUtilidadKeyTyped(evt);
            }
        });

        btnCalcular.setText("Calcular Precio");
        btnCalcular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnCalcularFocusGained(evt);
            }
        });
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        spCantidad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        spCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                spCantidadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                spCantidadKeyTyped(evt);
            }
        });

        spCantidadReserva.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        spCantidadReserva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                spCantidadReservaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                spCantidadReservaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIdArticulo)
                    .addComponent(txtNomArticulo)
                    .addComponent(btoUnidad, 0, 362, Short.MAX_VALUE)
                    .addComponent(txtPrecioCompra)
                    .addComponent(txtPrecioVenta)
                    .addComponent(spCantidad)
                    .addComponent(spCantidadReserva))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtPorcUtilidad)
                        .addComponent(btnCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                    .addComponent(jLabel8))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btoUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(spCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtPorcUtilidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(spCantidadReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 780, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void buscarCodArticulo()throws PDVException{
        try{
            inventario=clpdv.buscarArticuloPorCodigo(txtIdArticulo.getText());
            if(inventario==null){
                
            }else{
                JOptionPane.showMessageDialog(null,"El Articulo Código [ " + txtIdArticulo.getText() +" ] Ya Existe en la Base de Datos,Favor Verificar!!!","Atención",JOptionPane.ERROR_MESSAGE);
                txtIdArticulo.setText("");
                txtIdArticulo.grabFocus();
            }
        }catch (PDVException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    public void cerrar(){
         try {
             usuario = clpdv.buscarPorId(txtUsuario.getText());
         } catch (PDVException ex) {
             Logger.getLogger(VInventario.class.getName()).log(Level.SEVERE, null, ex);
         }
        
             if(usuario.getRol().equals("DEPENDIENTE")){
                
                    dispose();
            try {
                unUsuario=clpdv.buscarPorCed(txtUsuario.getText());
            } catch (PDVException ex) {
                Logger.getLogger(VInventario.class.getName()).log(Level.SEVERE, null, ex);
            }
                    if(unUsuario==null){
                        
                    }else{
                         VMenuAdmin menuAdmin=new VMenuAdmin();
                         menuAdmin.setVisible(true);
                         VMenuAdmin.txtUsuario.setText(txtUsuario.getText());
                         if(unUsuario.getCompras().equals("SI")){
                             VMenuAdmin.btnCompras.setEnabled(true);
                        }else{
                             VMenuAdmin.btnCompras.setEnabled(false);
                        }
                        if(unUsuario.getClientes().equals("SI")){
                             VMenuAdmin.btnClientes.setEnabled(true);
                        }else{
                             VMenuAdmin.btnClientes.setEnabled(false);
                        }
                        if(unUsuario.getProveedores().equals("SI")){
                            VMenuAdmin.btnProveedor.setEnabled(true);
                        }else{
                            VMenuAdmin.btnProveedor.setEnabled(false);
                        }
                        if(unUsuario.getInventario().equals("SI")){
                             VMenuAdmin.btnInventario.setEnabled(true);
                        }else{
                             VMenuAdmin.btnInventario.setEnabled(false);
                        }
                        if(unUsuario.getPagos().equals("SI")){
                            VMenuAdmin.btnPagos.setEnabled(true);
                        }else{
                            VMenuAdmin.btnPagos.setEnabled(false);
                        }
                        if(unUsuario.getConsignacion().equals("SI")){
                            VMenuAdmin.btnVentasConsignacion.setEnabled(true);
                        }else{
                            VMenuAdmin.btnVentasConsignacion.setEnabled(false);
                        }
                        if(unUsuario.getReportes().equals("SI")){
                             VMenuAdmin.btnReportes.setEnabled(true);
                        }else{
                             VMenuAdmin.btnReportes.setEnabled(false);
                        }
                        if(unUsuario.getFacturacion().equals("SI")){
                            VMenuAdmin.btnVentas.setEnabled(true);
                        }else{
                            VMenuAdmin.btnVentas.setEnabled(false);
                        }
                    }
             }else{
                 if(usuario.getRol().equals("ADMINISTRADOR")){
                     dispose();
                      VMenuAdmin menu = new VMenuAdmin();
                     menu.setVisible(true);
                     VMenuAdmin.txtUsuario.setText(txtUsuario.getText());
                 }
             }
    }
    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        
       
         
         cerrar();
    
      
        
    }//GEN-LAST:event_btnCerrarActionPerformed

  
    private void txtNomArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomArticuloActionPerformed
        // TODO add your handling code here:
        evt.setSource((char) KeyEvent.VK_CLEAR);
        spCantidad.requestFocus();// al presionar enter mandas el cursor a jTextField2
    }//GEN-LAST:event_txtNomArticuloActionPerformed

    private void txtPrecioCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioCompraActionPerformed
        // TODO add your handling code here:
        evt.setSource((char) KeyEvent.VK_CLEAR);
        txtPorcUtilidad.requestFocus();// al presionar enter mandas el cursor a jTextField2
        
        
    }//GEN-LAST:event_txtPrecioCompraActionPerformed

    private void txtPrecioVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioVentaActionPerformed
        // TODO add your handling code here:
        evt.setSource((char) KeyEvent.VK_CLEAR);
        spCantidadReserva.requestFocus();// al presionar enter mandas el cursor a jTextField2
    }//GEN-LAST:event_txtPrecioVentaActionPerformed

    private void txtNomArticuloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomArticuloKeyTyped
        // TODO add your handling code here:
        char charecter = evt.getKeyChar();
        if (Character.isLowerCase(charecter)) {
            evt.setKeyChar(Character.toUpperCase(charecter));
        }
    }//GEN-LAST:event_txtNomArticuloKeyTyped

    private void txtPrecioCompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioCompraKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isLetter(c)) {
              getToolkit().beep();
              evt.consume();
              
              JOptionPane.showMessageDialog(null,"No puede ingresar letras!!!,El Usuario es su Número de Cédula","Error",JOptionPane.ERROR_MESSAGE);
        }      
    }//GEN-LAST:event_txtPrecioCompraKeyTyped

    private void txtPrecioVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioVentaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioVentaKeyTyped

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        if(txtPorcUtilidad.getText().equals("")){
            txtPorcUtilidad.grabFocus();
            txtPrecioVenta.setText("");
        }else{
            calcularPrecioVenta();
        }
        
        
    }//GEN-LAST:event_btnCalcularActionPerformed
    public void calcularPrecioVenta(){
        float precioVenta=0;
        float utilidad=0;
        float precioCompra=0;
        
        DecimalFormat formato = new DecimalFormat("#,###.00");
        
        if(txtPorcUtilidad.getText().equals("")){
            txtPrecioVenta.setText("");
            
        }else{
            utilidad= Float.parseFloat(txtPorcUtilidad.getText());
            precioCompra= Float.parseFloat(txtPrecioCompra.getText());
            precioVenta=(utilidad/100+1)*precioCompra;
        
       
        //java.text.DecimalFormat formatoSalidaDecimal = new java.text.DecimalFormat("0.00");//para dos decimales  
        
        txtPrecioVenta.setText(formato.format(precioVenta));
        
        }
        
        
        
    }
    private void txtPorcUtilidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPorcUtilidadKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isLetter(c)) {
              getToolkit().beep();
              evt.consume();
              
              JOptionPane.showMessageDialog(null,"No puede ingresar letras!!!,El Usuario es su Número de Cédula","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtPorcUtilidadKeyTyped

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        float precioCompra=Float.parseFloat(txtPrecioCompra.getText());
        try {
             // TODO add your handling code here:
             inventario = clpdv.buscarArticuloPorCodigo(txtIdArticulo.getText());
         } catch (PDVException ex) {
             Logger.getLogger(VInventario.class.getName()).log(Level.SEVERE, null, ex);
         }
         
         if(txtIdArticulo.getText().equals("") || txtNomArticulo.getText().equals("") || txtPrecioCompra.getText().equals("") || txtPrecioVenta.getText().equals("")){
             JOptionPane.showMessageDialog(null,"No pueden haber campos vacíos","Atención",JOptionPane.ERROR_MESSAGE);
         }else{
             if(inventario==null){
                 try {
                     crearInventario(precioCompra);
                 } catch (PDVException ex) {
                     Logger.getLogger(VInventario.class.getName()).log(Level.SEVERE, null, ex);
                 }
             }else{
                 JOptionPane.showMessageDialog(null,"El Artículo Código ["+ txtIdArticulo.getText() + "] Ya existe favor Verificar!!!","Atención",JOptionPane.ERROR_MESSAGE);
                 limpiar();
             }
         }
        
        
    }//GEN-LAST:event_btnAgregarActionPerformed
    public void crearInventario(float pPrecioCompra)throws PDVException{
       DecimalFormat formato = new DecimalFormat("#,###.00"); 
       if(txtPorcUtilidad.getText().equals("")){
            
        }else{
            txtPrecioCompra.setText(formato.format(pPrecioCompra));
            
        }
       
        try{
            inventario=clpdv.buscarArticuloPorCodigo(txtIdArticulo.getText());
        }catch (PDVException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(inventario==null){
                clpdv.crearInventario(txtIdArticulo.getText(),
                                      txtNomArticulo.getText(),
                                     (String) btoUnidad.getSelectedItem(),
                                      (int)spCantidad.getValue(),
                                      (txtPrecioCompra.getText()),
                                      txtPrecioVenta.getText(),
                                      ((int)spCantidadReserva.getValue()));
                JOptionPane.showMessageDialog(null,"Registro Guardado Satisfactoriamente","Atención",JOptionPane.INFORMATION_MESSAGE);
                limpiar();
            }else{
            JOptionPane.showMessageDialog(null,"El Artículo Código ["+ txtIdArticulo.getText() +"]  Ya Existe, favor Verificar!!!","Atención",JOptionPane.ERROR_MESSAGE);
                limpiar();
        }
    }
   
    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtIdArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdArticuloActionPerformed
        // TODO add your handling code here:
         evt.setSource((char) KeyEvent.VK_CLEAR);
        txtNomArticulo.requestFocus();// al presionar enter mandas el cursor a jTextField2
         try {
             buscarCodArticulo();
         } catch (PDVException ex) {
             Logger.getLogger(VInventario.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_txtIdArticuloActionPerformed

    private void spCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spCantidadKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isLetter(c)) {
              getToolkit().beep();
              evt.consume();
              
              JOptionPane.showMessageDialog(null,"No puede ingresar letras!!!,El Usuario es su Número de Cédula","Error",JOptionPane.ERROR_MESSAGE);
        }     
    }//GEN-LAST:event_spCantidadKeyTyped

    private void spCantidadReservaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spCantidadReservaKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isLetter(c)) {
              getToolkit().beep();
              evt.consume();
              
              JOptionPane.showMessageDialog(null,"No puede ingresar letras!!!,El Usuario es su Número de Cédula","Error",JOptionPane.ERROR_MESSAGE);
        }     
    }//GEN-LAST:event_spCantidadReservaKeyTyped

    private void txtPorcUtilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPorcUtilidadActionPerformed
        // TODO add your handling code here:
          evt.setSource((char) KeyEvent.VK_CLEAR);
        btnCalcular.requestFocus();// al presionar enter mandas el cursor a jTextField2
        btnCalcular.doClick();
    }//GEN-LAST:event_txtPorcUtilidadActionPerformed

    private void txtIdArticuloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdArticuloKeyTyped
        // TODO add your handling code here:
         char charecter = evt.getKeyChar();
        if (Character.isLowerCase(charecter)) {
            evt.setKeyChar(Character.toUpperCase(charecter));
        }
    }//GEN-LAST:event_txtIdArticuloKeyTyped

    private void txtPorcUtilidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPorcUtilidadKeyReleased
        // TODO add your handling code here:
       calcularPrecioVenta();
    }//GEN-LAST:event_txtPorcUtilidadKeyReleased

    private void txtNomArticuloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomArticuloKeyPressed
        // TODO add your handling code here:
        if(KeyEvent.getKeyText(evt.getKeyCode()).equals("Escape")){
          cerrar();
         }
    }//GEN-LAST:event_txtNomArticuloKeyPressed

    private void btoUnidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btoUnidadKeyPressed
        // TODO add your handling code here:
       if(KeyEvent.getKeyText(evt.getKeyCode()).equals("Escape")){
          cerrar();
         }
    }//GEN-LAST:event_btoUnidadKeyPressed

    private void spCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spCantidadKeyPressed
        // TODO add your handling code here:
        if(KeyEvent.getKeyText(evt.getKeyCode()).equals("Escape")){
          cerrar();
         }
    }//GEN-LAST:event_spCantidadKeyPressed

    private void txtPrecioCompraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioCompraKeyPressed
        // TODO add your handling code here:
        if(KeyEvent.getKeyText(evt.getKeyCode()).equals("Escape")){
          cerrar();
         }
    }//GEN-LAST:event_txtPrecioCompraKeyPressed

    private void txtPorcUtilidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPorcUtilidadKeyPressed
        // TODO add your handling code here:
       if(KeyEvent.getKeyText(evt.getKeyCode()).equals("Escape")){
          cerrar();
         }
    }//GEN-LAST:event_txtPorcUtilidadKeyPressed

    private void btnCalcularFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnCalcularFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnCalcularFocusGained

    private void spCantidadReservaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spCantidadReservaKeyPressed
        // TODO add your handling code here:
        if(KeyEvent.getKeyText(evt.getKeyCode()).equals("Escape")){
          cerrar();
         }
    }//GEN-LAST:event_spCantidadReservaKeyPressed

    private void txtIdArticuloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdArticuloKeyPressed
        // TODO add your handling code here:
        if(KeyEvent.getKeyText(evt.getKeyCode()).equals("Escape")){
          cerrar();
         }
    }//GEN-LAST:event_txtIdArticuloKeyPressed

    private void txtPrecioVentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioVentaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioVentaKeyPressed

    public void limpiar(){
        txtIdArticulo.setText("");
        txtNomArticulo.setText("");
        spCantidad.setValue(0);
        txtPrecioCompra.setText("");
        txtPrecioVenta.setText("");
        txtPorcUtilidad.setText("");
        spCantidadReserva.setValue(0);
        txtIdArticulo.grabFocus();
    }
    /**
     * @param args the command line arguments
     */
    private CLPDV clpdv;
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VInventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> btoUnidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner spCantidad;
    private javax.swing.JSpinner spCantidadReserva;
    private javax.swing.JTextField txtIdArticulo;
    private javax.swing.JTextField txtNomArticulo;
    private javax.swing.JTextField txtPorcUtilidad;
    private javax.swing.JTextField txtPrecioCompra;
    private javax.swing.JTextField txtPrecioVenta;
    public static javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
