/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.Image;
import java.awt.Toolkit;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Erick Cordero
 */
public class VMenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form VMenuAdmin
     */
    public VMenuAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTipoUsuario = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        btnInventario = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnProveedor = new javax.swing.JButton();
        btnCompras = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnPagos = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnVentasConsignacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Menu del Administrador");
        setIconImage(getIconImage());
        setMaximumSize(new java.awt.Dimension(1451, 979));
        setMinimumSize(new java.awt.Dimension(1451, 979));
        setPreferredSize(new java.awt.Dimension(1451, 979));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInventario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/productos.png"))); // NOI18N
        btnInventario.setToolTipText("Inclusión de Artículos");
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 300, 270));

        btnVentas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/facturacion.jpg"))); // NOI18N
        btnVentas.setToolTipText("Modulo de Facturación");
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        getContentPane().add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 300, 250));

        btnProveedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/proveedores.jpg"))); // NOI18N
        btnProveedor.setToolTipText("Inclusión de Proveedores");
        btnProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(btnProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 300, 270));

        btnCompras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/comprass.jpg"))); // NOI18N
        btnCompras.setToolTipText("Modulo de Compras");
        btnCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprasActionPerformed(evt);
            }
        });
        getContentPane().add(btnCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 300, 270));

        btnClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clientes.jpg"))); // NOI18N
        btnClientes.setToolTipText("Inclusión de Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        getContentPane().add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 300, 250));

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.jpg"))); // NOI18N
        btnSalir.setToolTipText("Salir del Sistema");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 540, 300, 240));

        btnPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CxC.png"))); // NOI18N
        btnPagos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPagos.setToolTipText("Abonos a las cuentas por Cobrar");
        btnPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagosActionPerformed(evt);
            }
        });
        getContentPane().add(btnPagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 300, 250));

        btnReportes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportes.png"))); // NOI18N
        btnReportes.setToolTipText("Menu de Reportes");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        getContentPane().add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 20, 300, 270));

        btnVentasConsignacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ventasConsignacion.jpg"))); // NOI18N
        btnVentasConsignacion.setToolTipText("Cierre Ventas a Consignacion");
        btnVentasConsignacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasConsignacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnVentasConsignacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 290, 300, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
        dispose();
        VClientes clientes = new VClientes();
        clientes.setVisible(true);
        VClientes.txtUsuario.setText(txtUsuario.getText());
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedorActionPerformed
        // TODO add your handling code here:
        dispose();
        VProveedores proveedores =new VProveedores();
        proveedores.setVisible(true);
        VProveedores.txtUsuario.setText(txtUsuario.getText());
    }//GEN-LAST:event_btnProveedorActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        // TODO add your handling code here:
        dispose();
        VInventario inventario = new VInventario();
        inventario.setVisible(true);
        VInventario.txtUsuario.setText(txtUsuario.getText());
        
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprasActionPerformed
        // TODO add your handling code here:
        dispose();
        VCompras compras = new VCompras();
        compras.setVisible(true);
        VCompras.txtUsuario.setText(txtUsuario.getText());
        
    }//GEN-LAST:event_btnComprasActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        // TODO add your handling code here:
        dispose();
       
        try {
            VVentas ventas;
            ventas = new VVentas();
            ventas.setVisible(true);
        } catch (ParseException ex) {
            Logger.getLogger(VMenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        VVentas.txtUsuario.setText(txtUsuario.getText());
        
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagosActionPerformed
        // TODO add your handling code here:
        dispose();
        VPagos pagos=new VPagos();
        pagos.setVisible(true);
        VPagos.txtUsuario.setText(txtUsuario.getText());
    }//GEN-LAST:event_btnPagosActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
        dispose();
        VReportes reporte=new VReportes();
        reporte.setVisible(true);
        VReportes.txtUsuario.setText(txtUsuario.getText());
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnVentasConsignacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasConsignacionActionPerformed
        // TODO add your handling code here:
        dispose();
        VVentasConsignacion consignacion = new VVentasConsignacion();
        consignacion.setVisible(true);
        VVentasConsignacion.txtUsuario.setText(txtUsuario.getText());
        
              
    }//GEN-LAST:event_btnVentasConsignacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VMenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnClientes;
    public static javax.swing.JButton btnCompras;
    public static javax.swing.JButton btnInventario;
    public static javax.swing.JButton btnPagos;
    public static javax.swing.JButton btnProveedor;
    public static javax.swing.JButton btnReportes;
    private javax.swing.JButton btnSalir;
    public static javax.swing.JButton btnVentas;
    public static javax.swing.JButton btnVentasConsignacion;
    public static javax.swing.JTextField txtTipoUsuario;
    public static javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
