/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Objects.*;
import Reportes.ReporteCierreCajaContado;
import Reportes.ReporteCierreCredito;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author Erick Cordero
 */
public class VReportes extends javax.swing.JFrame {
private Ventas venta;
private Pagos pago;

private Account unaCuenta;
private OpcionesUsuario unUsuario;
private Usuario usuario;
    /**
     * Creates new form VReportes
     */
    public VReportes() {
        initComponents();
        venta=null;
        pago=null;
        unaCuenta=null;
        unUsuario=null;
        usuario=null;
        
        clpdv = new CLPDV();
        this.setLocationRelativeTo(null);
        dpFechaActual.setDateToToday();
         

    }
    public void cerrar(){
         try {
             usuario = clpdv.buscarPorId(txtUsuario.getText());
         } catch (PDVException ex) {
             Logger.getLogger(VInventario.class.getName()).log(Level.SEVERE, null, ex);
         }
        
             if(usuario.getRol().equals("DEPENDIENTE")){
                
                    dispose();
            try {
                unUsuario=clpdv.buscarPorCed(txtUsuario.getText());
            } catch (PDVException ex) {
                Logger.getLogger(VInventario.class.getName()).log(Level.SEVERE, null, ex);
            }
                    if(unUsuario==null){
                        
                    }else{
                         VMenuAdmin menuAdmin=new VMenuAdmin();
                         menuAdmin.setVisible(true);
                         VMenuAdmin.txtUsuario.setText(txtUsuario.getText());
                         if(unUsuario.getCompras().equals("SI")){
                             VMenuAdmin.btnCompras.setEnabled(true);
                        }else{
                             VMenuAdmin.btnCompras.setEnabled(false);
                        }
                        if(unUsuario.getClientes().equals("SI")){
                             VMenuAdmin.btnClientes.setEnabled(true);
                        }else{
                             VMenuAdmin.btnClientes.setEnabled(false);
                        }
                        if(unUsuario.getProveedores().equals("SI")){
                            VMenuAdmin.btnProveedor.setEnabled(true);
                        }else{
                            VMenuAdmin.btnProveedor.setEnabled(false);
                        }
                        if(unUsuario.getInventario().equals("SI")){
                             VMenuAdmin.btnInventario.setEnabled(true);
                        }else{
                             VMenuAdmin.btnInventario.setEnabled(false);
                        }
                        if(unUsuario.getPagos().equals("SI")){
                            VMenuAdmin.btnPagos.setEnabled(true);
                        }else{
                            VMenuAdmin.btnPagos.setEnabled(false);
                        }
                        if(unUsuario.getConsignacion().equals("SI")){
                            VMenuAdmin.btnVentasConsignacion.setEnabled(true);
                        }else{
                            VMenuAdmin.btnVentasConsignacion.setEnabled(false);
                        }
                        if(unUsuario.getReportes().equals("SI")){
                             VMenuAdmin.btnReportes.setEnabled(true);
                        }else{
                             VMenuAdmin.btnReportes.setEnabled(false);
                        }
                        if(unUsuario.getFacturacion().equals("SI")){
                            VMenuAdmin.btnVentas.setEnabled(true);
                        }else{
                            VMenuAdmin.btnVentas.setEnabled(false);
                        }
                    }
             }else{
                 if(usuario.getRol().equals("ADMINISTRADOR")){
                     dispose();
                      VMenuAdmin menu = new VMenuAdmin();
                     menu.setVisible(true);
                     VMenuAdmin.txtUsuario.setText(txtUsuario.getText());
                 }
             }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsuario = new javax.swing.JTextField();
        btnCxC = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnCxCxCliente = new javax.swing.JButton();
        btnCierre = new javax.swing.JButton();
        dpFechaActual = new com.github.lgooddatepicker.components.DatePicker();
        btnReporteFacturas = new javax.swing.JButton();
        btnReimprimirFactura = new javax.swing.JButton();
        btnFacturasCompras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu Reportes");
        setIconImage(getIconImage());
        setMaximumSize(new java.awt.Dimension(1451, 979));
        setMinimumSize(new java.awt.Dimension(1451, 979));
        setName("frmMenuReportes"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1451, 979));
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCxC.setText("CxC por Fecha");
        btnCxC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCxC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCxCActionPerformed(evt);
            }
        });
        getContentPane().add(btnCxC, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 250, 50));

        btnSalir.setText("Salir");
        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, 250, 50));

        btnCxCxCliente.setText("CxC por Cliente");
        btnCxCxCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCxCxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCxCxClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnCxCxCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 250, 50));

        btnCierre.setText("Cierre de Caja");
        btnCierre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCierreActionPerformed(evt);
            }
        });
        getContentPane().add(btnCierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, 250, 50));

        dpFechaActual.setEnabled(false);
        getContentPane().add(dpFechaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(967, 11, 226, -1));

        btnReporteFacturas.setText("Facturas de Ventas por Fechas");
        btnReporteFacturas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReporteFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteFacturasActionPerformed(evt);
            }
        });
        getContentPane().add(btnReporteFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 250, 50));

        btnReimprimirFactura.setText("Reimprimir una Factura de Venta");
        btnReimprimirFactura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReimprimirFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReimprimirFacturaActionPerformed(evt);
            }
        });
        getContentPane().add(btnReimprimirFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 250, 50));

        btnFacturasCompras.setText("Facturas de Compras por Fechas");
        btnFacturasCompras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnFacturasCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturasComprasActionPerformed(evt);
            }
        });
        getContentPane().add(btnFacturasCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 250, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCxCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCxCActionPerformed
        // TODO add your handling code here:
        dispose();
        VReporteCxC reporteCxC =new VReporteCxC();
        reporteCxC.setVisible(true);
        VReporteCxC.txtUsuario.setText(txtUsuario.getText());
        
    }//GEN-LAST:event_btnCxCActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        cerrar();
        
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCxCxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCxCxClienteActionPerformed
        // TODO add your handling code here:
        dispose();
        VReporteCxcCliente reporteCliente=new VReporteCxcCliente();
        reporteCliente.setVisible(true);
        VReporteCxcCliente.txtUsuario.setText(txtUsuario.getText());
       
    }//GEN-LAST:event_btnCxCxClienteActionPerformed

    private void btnCierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCierreActionPerformed
        dispose();
        
    try {
        VCierreCajaDiario cierreCaja;
        cierreCaja = new VCierreCajaDiario();
        cierreCaja.setVisible(true);
        VCierreCajaDiario.txtUsuario.setText(txtUsuario.getText());
    } catch (Exception ex) {
        Logger.getLogger(VReportes.class.getName()).log(Level.SEVERE, null, ex);
    }
        
        
    }//GEN-LAST:event_btnCierreActionPerformed

    private void btnReporteFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteFacturasActionPerformed
        // TODO add your handling code here:
        dispose();
        VReporteFacturas facturas=new VReporteFacturas();
        facturas.setVisible(true);
        VReporteFacturas.txtUsuario.setText(txtUsuario.getText());
    }//GEN-LAST:event_btnReporteFacturasActionPerformed

    private void btnReimprimirFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReimprimirFacturaActionPerformed
        // TODO add your handling code here:
        dispose();
        VModalReimprimirFactura reimprimir = new VModalReimprimirFactura();
        reimprimir.setVisible(true);
        VModalReimprimirFactura.txtUsuario.setText(txtUsuario.getText());
    }//GEN-LAST:event_btnReimprimirFacturaActionPerformed

    private void btnFacturasComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturasComprasActionPerformed
        // TODO add your handling code here:
        dispose();
        VReporteFacturasDeCompra facturasCompra = new VReporteFacturasDeCompra();
        facturasCompra.setVisible(true);
        VReporteFacturasDeCompra.txtUsuario.setText(txtUsuario.getText());
    }//GEN-LAST:event_btnFacturasComprasActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        if(KeyEvent.getKeyText(evt.getKeyCode()).equals("Escape")){
            dispose();
            VMenuAdmin menu=new VMenuAdmin();
            menu.setVisible(true);
         }
    }//GEN-LAST:event_formKeyPressed
    public void buscarFecha()throws PDVException, SQLException, JRException, ParseException{
         float totalGeneral=0;
         String pTotal="";
         String tipoVenta="";
          DecimalFormat formato = new DecimalFormat("#,###.00");
        ArrayList<Ventas> ventas=new ArrayList<>();
    
    try {
        ventas=clpdv.buscarFechaVenta(dpFechaActual.getDate());
        
    } catch (PDVException ex) {
        Logger.getLogger(VReportes.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    if (ventas==null){
        
    }else{
  
        for(int i=0;i<ventas.size();i++){
            LocalDate fecha=dpFechaActual.getDate();
            LocalDate fecha2=ventas.get(i).getFechaVenta();
            tipoVenta=ventas.get(i).getTipoVenta();
           if(fecha2.equals(fecha)&& tipoVenta.equals("CONTADO")){
                String total=ventas.get(i).getTotal();
                float totalFlt;
                Number nTotal = java.text.NumberFormat.getInstance().parse(total);
                totalFlt=nTotal.floatValue();
                totalGeneral=(totalGeneral+totalFlt);
                pTotal=formato.format(totalGeneral);
            
                
           } 
       
        }
    }
    reporte(tipoVenta,dpFechaActual.getDate(),pTotal);
    }
    public void reporte(String pTipoVenta, LocalDate pFecha, String pTotal)throws PDVException, SQLException, JRException{
        try{
            ReporteCierreCajaContado cierreContado=new ReporteCierreCajaContado();
            Date fechaVenta = java.sql.Date.valueOf(pFecha);
            cierreContado.ReportCierre(pTipoVenta,fechaVenta,pTotal);
        }catch(JRException | SQLException ex){
            Logger.getLogger(ReporteCierreCajaContado.class.getName()).log(Level.SEVERE,null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
     private  CLPDV clpdv;
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VReportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCierre;
    private javax.swing.JButton btnCxC;
    private javax.swing.JButton btnCxCxCliente;
    private javax.swing.JButton btnFacturasCompras;
    private javax.swing.JButton btnReimprimirFactura;
    private javax.swing.JButton btnReporteFacturas;
    private javax.swing.JButton btnSalir;
    private com.github.lgooddatepicker.components.DatePicker dpFechaActual;
    protected static javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
