/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Objects.*;
import static UI.VVentas.txtArticulo;
import static UI.VVentas.txtCantidad;
import static UI.VVentas.txtCliente;
import static UI.VVentas.txtIdArticulo;
import static UI.VVentas.txtPrecioVenta;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Erick Cordero
 */
public class VVentasConsignacion extends javax.swing.JFrame {
private Inventario inventario;
private Ventas venta;

private Account unaCuenta;
private OpcionesUsuario unUsuario;
private Usuario usuario;
    /**
     * Creates new form VVentasConsignacion
     */
    public VVentasConsignacion() {
        initComponents();
        this.setLocationRelativeTo(null);
        dpFechaActual.setDateToToday();
        inventario=null;
        unaCuenta=null;
        unUsuario=null;
        usuario=null;
        
        venta=null;
        txtNoFactura.requestFocus();
         clpdv = new CLPDV();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIdVenta = new javax.swing.JTextField();
        txtCliente = new javax.swing.JTextField();
        txtCantActual = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNoFactura = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTotalVenta = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtIdArticulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtArticulo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPrecioVenta = new javax.swing.JTextField();
        txtCantDevolver = new javax.swing.JLabel();
        spCantidadDevuelta = new javax.swing.JSpinner();
        btnBuscarIdArticulo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnDevolver = new javax.swing.JButton();
        dpFechaActual = new com.github.lgooddatepicker.components.DatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconImage(getIconImage());
        setMaximumSize(new java.awt.Dimension(1451, 979));
        setMinimumSize(new java.awt.Dimension(1451, 979));
        setPreferredSize(new java.awt.Dimension(1451, 979));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ventas a Consignacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("No.Factura");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 70, -1));

        txtNoFactura.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNoFactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNoFacturaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNoFacturaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNoFacturaKeyTyped(evt);
            }
        });
        jPanel1.add(txtNoFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 140, 30));

        jLabel2.setText("Total Venta");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 70, -1));

        txtTotalVenta.setEditable(false);
        txtTotalVenta.setBackground(new java.awt.Color(153, 255, 153));
        txtTotalVenta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtTotalVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 140, 30));

        btnBuscar.setText("jButton1");
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 30, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 730, 170));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Articulos a Devolver", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("COD.Artículo:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 80, -1));

        txtIdArticulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtIdArticulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdArticuloKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdArticuloKeyReleased(evt);
            }
        });
        jPanel3.add(txtIdArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 460, 30));

        jLabel4.setText("Articulo");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 50, -1));

        txtArticulo.setEditable(false);
        txtArticulo.setBackground(new java.awt.Color(153, 255, 153));
        txtArticulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(txtArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 540, 30));

        jLabel5.setText("Precio Venta");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 70, -1));

        txtPrecioVenta.setEditable(false);
        txtPrecioVenta.setBackground(new java.awt.Color(153, 255, 153));
        txtPrecioVenta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(txtPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 540, 30));

        txtCantDevolver.setText("Devolucion");
        jPanel3.add(txtCantDevolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 70, -1));

        spCantidadDevuelta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        spCantidadDevuelta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                spCantidadDevueltaKeyPressed(evt);
            }
        });
        jPanel3.add(spCantidadDevuelta, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 540, 30));

        btnBuscarIdArticulo.setText("jButton1");
        jPanel3.add(btnBuscarIdArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 30, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 730, 270));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardar.setText("Cerrar Venta");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 110, 40));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 100, 40));

        btnDevolver.setText("Devolver");
        btnDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverActionPerformed(evt);
            }
        });
        jPanel2.add(btnDevolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 110, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, 670, 130));

        dpFechaActual.setEnabled(false);
        getContentPane().add(dpFechaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, 340, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void buscarNoFactura(){
        int IdFactura;
        String tipoVenta="";
        String totalVentConsig;
        DecimalFormat formato = new DecimalFormat("#,###.00");
        float totalVenta=0;
        String cliente;
        
        IdFactura=Integer.parseInt(txtNoFactura.getText());
        
        ArrayList<Ventas> ventas= new ArrayList<>();
        
        try {
            ventas= clpdv.buscarVentasConsignacion(IdFactura);
            
        } catch (PDVException ex) {
            Logger.getLogger(VVentasConsignacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (ventas==null){
           /* JOptionPane.showMessageDialog(null,"La Factura No. " + IdFactura + " No existe en la Base de Datos, favor verificar","Atención",JOptionPane.ERROR_MESSAGE);
            txtNoFactura.setText("");
            txtNoFactura.requestFocus();*/
        }else{
           
          for(int i=0;i<ventas.size();i++){
              tipoVenta=ventas.get(i).getTipoVenta();
          }
          
          if(tipoVenta.equals("CERRADA")){
              JOptionPane.showMessageDialog(null,"El No.Factura a consignacion " + IdFactura + " ya fue cerrada y no puede ser modificada!!!","Atención",JOptionPane.ERROR_MESSAGE);
              txtNoFactura.setText("");
              txtNoFactura.requestFocus();
          
          }else{
              if(tipoVenta.equals("CONSIGNACION")){
                
                for(int i=0; i <ventas.size();i++){
                    try { 
                    
                        Number nTotal = java.text.NumberFormat.getInstance().parse(ventas.get(i).getSubTotal());
                        float total=nTotal.floatValue();
                        totalVenta=totalVenta+total;
                        cliente=ventas.get(i).getCliente();
                        txtCliente.setText(cliente);
                        txtTotalVenta.setText(formato.format(totalVenta));
                        txtIdArticulo.requestFocus();
                    }catch (ParseException ex) {
                        Logger.getLogger(VVentasConsignacion.class.getName()).log(Level.SEVERE, null, ex);
                    }
               
                
                
            }
       
        }else{
              JOptionPane.showMessageDialog(null,"El No Factura buscado no es de Tipo Consignación, Favor Verificar","Atención",JOptionPane.ERROR_MESSAGE);
              txtNoFactura.setText("");
              txtNoFactura.requestFocus();
        }
        }
        }
    }
    public void cerrar(){
         try {
             usuario = clpdv.buscarPorId(txtUsuario.getText());
         } catch (PDVException ex) {
             Logger.getLogger(VInventario.class.getName()).log(Level.SEVERE, null, ex);
         }
        
             if(usuario.getRol().equals("DEPENDIENTE")){
                
                    dispose();
            try {
                unUsuario=clpdv.buscarPorCed(txtUsuario.getText());
            } catch (PDVException ex) {
                Logger.getLogger(VInventario.class.getName()).log(Level.SEVERE, null, ex);
            }
                    if(unUsuario==null){
                        
                    }else{
                         VMenuAdmin menuAdmin=new VMenuAdmin();
                         menuAdmin.setVisible(true);
                         VMenuAdmin.txtUsuario.setText(txtUsuario.getText());
                         if(unUsuario.getCompras().equals("SI")){
                             VMenuAdmin.btnCompras.setEnabled(true);
                        }else{
                             VMenuAdmin.btnCompras.setEnabled(false);
                        }
                        if(unUsuario.getClientes().equals("SI")){
                             VMenuAdmin.btnClientes.setEnabled(true);
                        }else{
                             VMenuAdmin.btnClientes.setEnabled(false);
                        }
                        if(unUsuario.getProveedores().equals("SI")){
                            VMenuAdmin.btnProveedor.setEnabled(true);
                        }else{
                            VMenuAdmin.btnProveedor.setEnabled(false);
                        }
                        if(unUsuario.getInventario().equals("SI")){
                             VMenuAdmin.btnInventario.setEnabled(true);
                        }else{
                             VMenuAdmin.btnInventario.setEnabled(false);
                        }
                        if(unUsuario.getPagos().equals("SI")){
                            VMenuAdmin.btnPagos.setEnabled(true);
                        }else{
                            VMenuAdmin.btnPagos.setEnabled(false);
                        }
                        if(unUsuario.getConsignacion().equals("SI")){
                            VMenuAdmin.btnVentasConsignacion.setEnabled(true);
                        }else{
                            VMenuAdmin.btnVentasConsignacion.setEnabled(false);
                        }
                        if(unUsuario.getReportes().equals("SI")){
                             VMenuAdmin.btnReportes.setEnabled(true);
                        }else{
                             VMenuAdmin.btnReportes.setEnabled(false);
                        }
                        if(unUsuario.getFacturacion().equals("SI")){
                            VMenuAdmin.btnVentas.setEnabled(true);
                        }else{
                            VMenuAdmin.btnVentas.setEnabled(false);
                        }
                    }
             }else{
                 if(usuario.getRol().equals("ADMINISTRADOR")){
                     dispose();
                      VMenuAdmin menu = new VMenuAdmin();
                     menu.setVisible(true);
                     VMenuAdmin.txtUsuario.setText(txtUsuario.getText());
                 }
             }
    }
        
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
       cerrar();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
        // TODO add your handling code here:
        float totalVenta;
        float precioVenta;
        float totalEfectivo;
        float subTotal;
        int cantActual;
        int cantDevuelta;
        int cantNueva;
        DecimalFormat formato = new DecimalFormat("#,###.00"); 
        
    try {
        Number nTotalVenta=java.text.NumberFormat.getInstance().parse(txtTotalVenta.getText());
        totalVenta=nTotalVenta.floatValue();
        
        Number nPrecioVenta=java.text.NumberFormat.getInstance().parse(txtPrecioVenta.getText());
        precioVenta=nPrecioVenta.floatValue();
        cantDevuelta=(int)spCantidadDevuelta.getValue();
        subTotal=(cantDevuelta*precioVenta);
        cantActual=Integer.parseInt(txtCantActual.getText());
        totalEfectivo=(totalVenta-subTotal);
        cantNueva=cantActual+(int)spCantidadDevuelta.getValue();
        txtTotalVenta.setText(formato.format(totalEfectivo));
        
        actualizarInventario(txtIdArticulo.getText(),cantNueva);
        txtIdArticulo.setText("");
        txtArticulo.setText("");
        spCantidadDevuelta.setValue(0);
        txtPrecioVenta.setText("");
        txtIdArticulo.requestFocus();
        
    } catch (ParseException | PDVException ex) {
        Logger.getLogger(VVentasConsignacion.class.getName()).log(Level.SEVERE, null, ex);
    }
        
        
        
    }//GEN-LAST:event_btnDevolverActionPerformed
    
    public void actualizarInventario(String pIdArticulo, int pCantidadDevuelta) throws PDVException{
        
        clpdv.actualizarInventario(pIdArticulo, pCantidadDevuelta);
        
    }
    private void txtNoFacturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoFacturaKeyTyped
        // TODO add your handling code here:
          // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isLetter(c)) {
              getToolkit().beep();
              evt.consume();
              
              JOptionPane.showMessageDialog(null,"No puede ingresar letras!!!,El dato a ingresar corresponde a un Dígito Numeral","Error",JOptionPane.ERROR_MESSAGE);
              
          }
           if (txtNoFactura.getText().length()>=9) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNoFacturaKeyTyped

    private void txtIdArticuloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdArticuloKeyReleased
        // TODO add your handling code here:
         buscarArticulo();
    }//GEN-LAST:event_txtIdArticuloKeyReleased

    private void txtNoFacturaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoFacturaKeyReleased
        // TODO add your handling code here:
          
    }//GEN-LAST:event_txtNoFacturaKeyReleased

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        int idVenta;
        buscarNoVenta();
        int cantidad;
        idVenta=buscarNoVenta();
        String subTotal;
        String tipoPago;
        String idArticulo;
        String nombreArticulo;
        String precioVenta;
        String tipoVenta;
        int idFactura;
        subTotal="0";
        
        tipoPago="CONTADO";
        
        cantidad=1;
        idArticulo="1";
        nombreArticulo="VENTA CONSIGNACION";
        precioVenta="0";
        tipoVenta="CERRADA";
        idFactura=Integer.parseInt(txtNoFactura.getText());
    try {
        clpdv.crearVenta(Integer.parseInt(txtIdVenta.getText()),
                idArticulo,
                nombreArticulo,
                precioVenta,
                cantidad,
                subTotal,
                txtTotalVenta.getText(),
                txtCliente.getText(),
                dpFechaActual.getDate(),
                tipoPago);
    } catch (PDVException ex) {
        Logger.getLogger(VVentasConsignacion.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    //actualiza la factura en la tabla de ventas para saber que ese num de factura
    //que era de consignacion ya fue cerrada y no se puede tocar mas en caso
    //de que el usuario vuelva a agregar ese num de factura en el modulo de cierre
    // de ventas a consignacion para que no pueda manipular nuevamente una factura
    //que ya fue cerrada
    try {
        clpdv.actualizarTotalVenta(idFactura,tipoVenta);
    } catch (PDVException ex) {
        Logger.getLogger(VVentasConsignacion.class.getName()).log(Level.SEVERE, null, ex);
    }
    JOptionPane.showMessageDialog(null,"Cierre de venta a Consignacion efectuado satisfactoriamente","Atención",JOptionPane.INFORMATION_MESSAGE);
    txtNoFactura.setText("");
    txtTotalVenta.setText("");
    txtNoFactura.requestFocus();
    
        
        
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNoFacturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoFacturaKeyPressed
        // TODO add your handling code here:
        if(KeyEvent.getKeyText(evt.getKeyCode()).equals("Escape")){
            cerrar();
         }
    }//GEN-LAST:event_txtNoFacturaKeyPressed

    private void txtIdArticuloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdArticuloKeyPressed
        // TODO add your handling code here:
        if(KeyEvent.getKeyText(evt.getKeyCode()).equals("Escape")){
           cerrar();
         }
    }//GEN-LAST:event_txtIdArticuloKeyPressed

    private void spCantidadDevueltaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spCantidadDevueltaKeyPressed
        // TODO add your handling code here:
        if(KeyEvent.getKeyText(evt.getKeyCode()).equals("Escape")){
            cerrar();
         }
    }//GEN-LAST:event_spCantidadDevueltaKeyPressed
    public int  buscarNoVenta(){
        int idVenta=0;
         try{
             venta=clpdv.buscarNoVenta();
             idVenta=(venta.getIdVenta()+1);
             txtIdVenta.setText(Integer.toString(idVenta));
             txtIdArticulo.grabFocus();
         }catch (Exception ex){
             Logger.getLogger(VClientes.class.getName()).log(Level.SEVERE,null, ex);
         }
         return idVenta;
    }
    public void buscarArticulo(){
        
    DecimalFormat formato = new DecimalFormat("#,###.00");   
    try {
        // TODO add your handling code here:
        inventario = clpdv.buscarArticuloPorCodigo(txtIdArticulo.getText());
    } catch (PDVException ex) {
        Logger.getLogger(VCompras.class.getName()).log(Level.SEVERE, null, ex);
    }
    if(inventario==null){
        //JOptionPane.showMessageDialog(null,"El Articulo Codigo [" + txtIdArticulo.getText() + "] no Existe en el inventario, favor Verificar!!!","Atención",JOptionPane.ERROR_MESSAGE);
        //txtIdArticulo.setText("");
        //txtIdArticulo.grabFocus();
    }else{
        String nombre = inventario.getNombreProducto();
        int cantidadActual = inventario.getCantidad();
        txtCantActual.setText(Integer.toString(cantidadActual));
        
        
        Number nPrecioVenta;
        Number nPrecioCompra;
             try {
                 nPrecioVenta = java.text.NumberFormat.getInstance().parse(inventario.getPrecioVentaUnd());
                 float precioVenta=nPrecioVenta.floatValue();
                 int cantidadInventario=inventario.getCantidad();
                 String precioCompra;
                 precioCompra= inventario.getPrecioCompraUnd();
                 txtPrecioVenta.setText(formato.format(precioVenta));
                 txtArticulo.setText(nombre);
                 txtPrecioVenta.setText(formato.format(precioVenta));
                 
                
             }catch (ParseException ex) {
                 Logger.getLogger(VVentasConsignacion.class.getName()).log(Level.SEVERE, null, ex);
             }
    }
    }
    /**
     * @param args the command line arguments
     */
   private CLPDV clpdv;
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VVentasConsignacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VVentasConsignacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VVentasConsignacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VVentasConsignacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VVentasConsignacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarIdArticulo;
    private javax.swing.JButton btnDevolver;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private com.github.lgooddatepicker.components.DatePicker dpFechaActual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSpinner spCantidadDevuelta;
    private javax.swing.JTextField txtArticulo;
    private javax.swing.JTextField txtCantActual;
    private javax.swing.JLabel txtCantDevolver;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtIdArticulo;
    private javax.swing.JTextField txtIdVenta;
    private javax.swing.JTextField txtNoFactura;
    private javax.swing.JTextField txtPrecioVenta;
    private javax.swing.JTextField txtTotalVenta;
    public static javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
